### ISSUE TITLE
BYML strictness

### ISSUE THREAD

**Issue by Makonede** [NiceneNerd/ukmm#10]
Many mods currently fail to install because of heavy BYML strictness; I64 instead of U64, StringRef instead of String64, or a missing node that the mod works fine without will all make mods uninstallable. The BYML strictness should be heavily decreased in order to allow some larger mods, such as SW, DAR, RotP, or HyRe, to be installed.

**Comment by NiceneNerd** [comment]
While it is definitely possible and probably desirable to allow the string types to be interchangeable (and they already are in a number of places), I'm not so sure about the numeric types, which would be both harder to make generic (given that Rust does not allow implicit conversions between numeric types like C or use a general purpose integer type like Python) and more likely to involve correctness issues. For missing nodes a few specific file types have workarounds, but these would be hard to generalize to all such cases.

I know Second Wind has been recently receiving updates to ensure it passes through UKMM, but I'd be curious to see where some of these other mods fail. I know some of them have technically incorrect shop/drop tables, but those two file types I have already added workarounds for. Any others turn up thus far?

**Comment by codemann8** [comment]
Relics of the Past v3.0 seems to fail as well, with a I32/U32 error

**Comment by NiceneNerd** [comment]
So this commit will probably solve the majority of this, except for mislabeled nodes: b06a98fcadbefc559213582c372b70f8aa0a4449

**Comment by Makonede** [comment]
nice nice, just waiting on nodes
