### ISSUE TITLE
Linkle (and Link) Upgradeable Armor Rebalance NX not able to convert bnp to ukmm mod

### ISSUE THREAD

**Issue by Gear4luffy1** [NiceneNerd/ukmm#100]
Hi im trying to install this mod [](https://gamebanana.com/mods/340011) and when installing i get this error

`Caused by:
    0: Failed to process SARC file Actor/Pack/Armor_243_Upper.bactorpack at `crates\uk-mod\src\pack.rs@341:22`
    1: Failed to parse resource Actor/Recipe/Armor_243_Upper.brecipe in SARC 01007EF00011E000/romfs/Actor/Pack/Armor_243_Upper.sbactorpack at `crates\uk-mod\src\pack.rs@479:73`
    2: Failed to parse resource Actor/Recipe/Armor_243_Upper.brecipe
    3: Parameter file missing key: Recipe missing item count`

I dont know if anyone else is having this problem but if someone knows how to fix it pls help

thanks :)

**Comment by NiceneNerd** [comment]
That is a problem with the mod; it needs to be corrected in the recipe file
