### ISSUE TITLE
Corrupt AocMainField.pack

### ISSUE THREAD

**Issue by ArchLeaders** [NiceneNerd/ukmm#104]
Some SARC files (specifically `AocMainField.pack`) are outputted from UKMM as valid SARCs, but cause the game to crash when loading a save. Copying the directly modified `AocMainField.pack` (edited with WildBits or SwitchToolbox) file into the graphicPacks works as expected.

The modified file inside the SARC is identical (comparing binary data) to the input file.

[Broken File](https://drive.google.com/file/d/14gxKC6quAjrYg1YT3ed1CbpiB1tlLu_P/view?usp=sharing) | [Working File](https://drive.google.com/file/d/1gPm_7iFlfxeHfhnGAzEeHOmSK_r8i5qv/view?usp=share_link)

**Comment by NiceneNerd** [comment]
Thus far I have not been able to replicate this. Is this happening when you use any mod that edits `AocMainField.pack`?

**Comment by ArchLeaders** [comment]
The only one I tested was my own mod, but I'll look around for others when I get a chance

**Comment by NiceneNerd** [comment]
I've made a couple potentially related changes, any further info?
