### ISSUE TITLE
Failed to apply mod changes (Better Shrine Rewards)

### ISSUE THREAD

**Issue by SupahDrivah1234** [NiceneNerd/ukmm#105]
Hello, using UKMM for the first time. I keep getting this error when installing the mod Better Shrine Rewards by Echocolat.

Failed to apply pending mod changes

Caused by:
    No base version for file Pack/Dungeon002.pack at `crates\uk-mod\src\unpack.rs@632:14`

**Comment by NiceneNerd** [comment]
Which mod download did you use? The UKMM version, I presume? I cannot replicate the error, nor apparently can the mod's author. This suggests something amiss with your dump, most probably.
