### ISSUE TITLE
Hyrule Rebalance 7.11 fails with "range end index out of range" error

### ISSUE THREAD

**Issue by bbugh** [NiceneNerd/ukmm#109]
When adding the Hyrule Rebalance v7.11 with ukmm latest 0.7.1, the error occurs:

> range end index 92 out of range for slice of length 91

This is the specific file:

https://gamebanana.com/mods/download/49532#FileInfo_970238

Possibly similar or related to #42?

**Comment by NiceneNerd** [comment]
Fixed with 3f445ea3a5a7369489ce7680127d93d9b6fc53d3
