### ISSUE TITLE
Mod option defaults

### ISSUE THREAD

**Issue by Benna96** [NiceneNerd/ukmm#11]
Currently, when packaging a mod, the UI

- allows specifying a default option for exclusive option groups, which gets saved to `meta.toml`
- doesn't offer a way of specifying defaults for multiple options groups, though `meta.toml` does seem to have a field for them (`defaults`). I tried adding in defaults manually by modifying this field

In either case, the specified defaults have no effect when installing the packaged mod.

**Comment by NiceneNerd** [comment]
Ah, yes, the missing default option for multiples is an oversight, shall fix. I'll also check into the use of defaults when installing.
