### ISSUE TITLE
Incorrect installation of the "Relics of the Past 3.1.2"

### ISSUE THREAD

**Issue by yehorb** [NiceneNerd/ukmm#112]
UKMM 0.8.0.

CEMU 2.0-36, [Relics of the Past 3.1.2](https://gamebanana.com/mods/414822).

Graphic Packs - FPS++ (60 fps), Extended Memory, Graphics, UKMM.

When the mod is installed using UKMM, I am experiencing crashes in the Great Plateau area, near the first Sheikah Tower spawn location. Or, strangely, after any Sneak Strike.

When the mod is installed using BCML, everything is working without crashes.

There are also differences in map objects between versions - UKMM has vanilla objects, while BCML has updated, mod-intended objects

<details>
	<summary>Map objects</summary>
 	<details>
		<summary>UKMM</summary>
		<img src="https://user-images.githubusercontent.com/17297726/236009360-98ea6583-b80a-421b-b527-57d2592dd862.png">
		<img src="https://user-images.githubusercontent.com/17297726/236009367-8842b7c6-dad2-4752-82c2-acd3d974faf2.png">
		<img src="https://user-images.githubusercontent.com/17297726/236009371-7ba7d9c6-6003-4fb6-a402-2e07c3bb1575.png">
	</details>
 	<details>
		<summary>BCML</summary>
		<img src="https://user-images.githubusercontent.com/17297726/236009465-9ef7ccef-5040-4669-962a-a36068bae7aa.png">
		<img src="https://user-images.githubusercontent.com/17297726/236009468-cbf675b1-ff51-4205-9d0f-376063bac905.png">
		<img src="https://user-images.githubusercontent.com/17297726/236009471-6e61e31a-e144-41e6-a6bc-e7dd6f8d6acd.png">
	</details>
</details>

It looks like UKMM is able to unpack and merge some of the mod files, but not all of them. I see the mod starting menu and tips, and some map objects are present, but not all of them.

Otherwise, I find UKMM a lot smoother and faster experience than BCML. I hope this merging issue can be resolved!

**Comment by NiceneNerd** [comment]
For diagnostic purposes, can you tell me if the map edits work if you add a blank (0 byte) file at `aoc/0010/Pack/AocMainField.pack` in the merged mod pack?

**Comment by yehorb** [comment]
Map edits do appear after adding the file to the `merged` directory at the path you provided.
The game still crashes after a Sneak Strike, which does not happen with BCML.

**Comment by NiceneNerd** [comment]
What's the timing on the Sneak Strike crash like? Does the attack animation complete? Does the enemy respond or finish dying?

**Comment by yehorb** [comment]
It looks like not every Sneak Strike breaks the game, I was able to successfully chain Sneak Strike the Blue Bokoblin, but not the Silver Moblin.
The game crashes a second after a Sneak Strike animation completes, and an enemy fell down. Wild guess - something like the animation of getting up is corrupted.
This is a quick recap, I am recording the gameplay for you.

**Comment by yehorb** [comment]
https://youtu.be/bZTqcAch34Q

**Comment by yehorb** [comment]
Also, it looks like Bokoblin in UKMM has less health, as it takes one more strike to take it out in BCML.
