### ISSUE TITLE
Failed to convert BNP to UKMM mod w/ Hyrule Rebalance

### ISSUE THREAD

**Issue by EncampedMars801** [NiceneNerd/ukmm#118]
Similar to the other issue, except with specifically Hyrule Rebalance. The v10 release of the mod used to work with more recent versions not installing, however now v10-v12 all error with the message pasted below. Also I'm using the latest build (git pulled and built locally) on Linux if that helps.

Failed to convert BNP to UKMM mod

Caused by:
    0: Failed to package mod root at /tmp/.tmpf2nxA7/options/1Hyrule Rebalance v7 Modular - MAIN for mod Hyrule Rebalance v7 at `crates/uk-mod/src/pack.rs@621:38`
    1: Failed to process SARC file Actor/Pack/Armor_270_Upper.bactorpack at `crates/uk-mod/src/pack.rs@378:22`
    2: Failed to parse resource Actor/Recipe/Armor_270_Upper.brecipe in SARC content/Actor/Pack/Armor_270_Upper.sbactorpack at `crates/uk-mod/src/pack.rs@502:73`
    3: Failed to parse resource Actor/Recipe/Armor_270_Upper.brecipe
    4: Parameter file missing key: Recipe missing item name

**Comment by EncampedMars801** [comment]
Further testing/tryingtogetthemodworking has revealed that if you extract the bnp, repackage it using version 8.1 of ukmm, and then try installing that it works fine. so uh, yeah

**Comment by EncampedMars801** [comment]
ok even further testing/tryingtogetthemodworking botw crashes right after finishing loading vulkan pipelines so uh ignore my previous message

**Comment by NiceneNerd** [comment]
This is an actual error in the specified recipe file which must be fixed in the mod. There are workarounds present for similar errors, but this one needs fixing.
