### ISSUE TITLE
Apple Silicon build fails

### ISSUE THREAD

**Issue by neebyA** [NiceneNerd/ukmm#119]
## Compiling on M1

I got this error when trying to build on an Apple Silicon Mac:
<details>
<summary>Error log</summary>
<br>
<pre>
  = note: ld: warning: directory not found for option '-Llib/zlib-ng'
          ld: warning: could not create compact unwind for _zng_deflateSetDictionary: registers 23 and 24 not saved contiguously in frame
          ld: warning: could not create compact unwind for _zng_deflateGetDictionary: registers 19 and 20 not saved contiguously in frame
          ld: warning: could not create compact unwind for _zng_deflateResetKeep: registers 19 and 20 not saved contiguously in frame
          ld: warning: could not create compact unwind for _zng_deflateReset: registers 19 and 20 not saved contiguously in frame
          ld: warning: could not create compact unwind for _zng_deflatePrime: registers 23 and 24 not saved contiguously in frame
          ld: warning: could not create compact unwind for _zng_deflateEnd: registers 19 and 20 not saved contiguously in frame
          ld: warning: could not create compact unwind for _zng_deflateInit2_: registers 25 and 26 not saved contiguously in frame
          ld: warning: could not create compact unwind for _zng_deflateInit_: registers 21 and 22 not saved contiguously in frame
          ld: warning: could not create compact unwind for _zng_deflateCopy: registers 19 and 20 not saved contiguously in frame
          ld: warning: could not create compact unwind for _deflate_stored: registers 27 and 28 not saved contiguously in frame
          ld: warning: could not create compact unwind for _zng_deflate: registers 25 and 26 not saved contiguously in frame
          ld: warning: could not create compact unwind for _zng_deflateSetParams: registers 21 and 22 not saved contiguously in frame
          ld: warning: could not create compact unwind for _deflate_fast: registers 23 and 24 not saved contiguously in frame
          ld: warning: could not create compact unwind for _deflate_medium: register 73 saved somewhere other than in frame
          ld: warning: could not create compact unwind for _deflate_slow: register 28 saved somewhere other than in frame
          ld: warning: could not create compact unwind for _insert_string_stub: register 22 saved somewhere other than in frame
          ld: warning: could not create compact unwind for _updatewindow.isra.0: registers 21 and 22 not saved contiguously in frame
          ld: warning: could not create compact unwind for _zng_inflateResetKeep: register 20 saved somewhere other than in frame
          ld: warning: could not create compact unwind for _zng_inflateReset: register 20 saved somewhere other than in frame
          ld: warning: could not create compact unwind for _zng_inflateInit2_: registers 21 and 22 not saved contiguously in frame
          ld: warning: could not create compact unwind for _zng_inflateInit_: register 22 saved somewhere other than in frame
          ld: warning: could not create compact unwind for _inflate_ensure_window: registers 19 and 20 not saved contiguously in frame
          ld: warning: could not create compact unwind for _zng_inflate: registers 27 and 28 not saved contiguously in frame
          ld: warning: could not create compact unwind for _zng_inflateGetDictionary: registers 19 and 20 not saved contiguously in frame
          ld: warning: could not create compact unwind for _zng_inflateSetDictionary: registers 19 and 20 not saved contiguously in frame
          ld: warning: could not create compact unwind for _zng_inflateSync: register 24 saved somewhere other than in frame
          ld: warning: could not create compact unwind for _zng_inflateCopy: registers 19 and 20 not saved contiguously in frame
          ld: warning: could not create compact unwind for _zng_inflateBackInit_: registers 19 and 20 not saved contiguously in frame
          ld: warning: could not create compact unwind for _zng_inflateBack: registers 27 and 28 not saved contiguously in frame
          ld: warning: could not create compact unwind for _zng_inflate_table: registers 27 and 28 not saved contiguously in frame
          ld: warning: could not create compact unwind for _zng_inflate_fast: registers 27 and 28 not saved contiguously in frame
          ld: warning: could not create compact unwind for _build_tree: registers 27 and 28 not saved contiguously in frame
          ld: warning: could not create compact unwind for _zng_tr_stored_block: registers 19 and 20 not saved contiguously in frame
          ld: warning: could not create compact unwind for _zng_tr_flush_block: registers 25 and 26 not saved contiguously in frame
          ld: warning: could not create compact unwind for _zng_uncompress2: register 28 saved somewhere other than in frame
          Undefined symbols for architecture arm64:
            "___emutls_get_address", referenced from:
                _zng_deflateReset in libroead-0f97a6bb97a75d55.rlib(deflate.c.o)
                _read_buf in libroead-0f97a6bb97a75d55.rlib(deflate.c.o)
                _zng_deflate in libroead-0f97a6bb97a75d55.rlib(deflate.c.o)
                _crc32_stub in libroead-0f97a6bb97a75d55.rlib(functable.c.o)
                _adler32_stub in libroead-0f97a6bb97a75d55.rlib(functable.c.o)
                _slide_hash_stub in libroead-0f97a6bb97a75d55.rlib(functable.c.o)
                _fill_window_stub in libroead-0f97a6bb97a75d55.rlib(functable.c.o)
                ...
          ld: symbol(s) not found for architecture arm64
          clang: error: linker command failed with exit code 1 (use -v to see invocation)
</pre>
</details>

This was working earlier, and I was able to narrow the breaking change to https://github.com/NiceneNerd/ukmm/commit/3f445ea3a5a7369489ce7680127d93d9b6fc53d3, which updated `roead` to 0.20.3. This would make the troublesome commit either https://github.com/NiceneNerd/roead/commit/42e8fac9ffc0f0ed2ae25bfebd00d9247ee1229f or https://github.com/NiceneNerd/roead/commit/8e923e99ba9a6482674ff5524e8ac84a4b1d022c, though I can't imagine why. I tested reverting `roead` back to 0.20.2 and the build succeeded.

The fact that this is a linker error and that the first line is `ld: warning: directory not found for option '-Llib/zlib-ng'` led me to believe that a linker flag is not being set properly. Why this only started showing up with 0.20.3 and only on Apple Silicon is a mystery to me; I can only hazard a guess that one of those commits could have had some weird effect on the mangling done by the Apple clang compiler.

Anyway, I found this [relevant StackOverflow post](https://stackoverflow.com/questions/41917096/how-do-i-make-rustc-link-search-relative-to-the-project-location) and [tried it out in my fork](https://github.com/neebyA/roead/commit/bcb04f19cd0922405740f959214126168b84205d). I edited `Cargo.toml` to use `roead` from my branch and the build succeeded again, on both Intel and ARM. I don't have much experience with Rust, so I'm not sure if there's a more preferred implementation for the fix than the one I did.

-----------
## Cross compiling on Intel
The above fix should work when compiling on an ARM Mac, but ideally we could cross-compile on Intel, and build an ARM binary as part of the release process with:
```
rustup target add aarch64-apple-darwin --toolchain nightly
cargo build --release --target=aarch64-apple-darwin
```
followed by using `lipo` to create a universal binary.

However, I also got linker errors from `roead` when trying this, and unlike on an actual M1, it seems that this cross compile has never actually worked. 

<details open>
<summary>Error log</summary>
<pre>
  = note: ld: warning: directory not found for option '-Llib/zlib-ng'
          ld: in /Users/neeby/Documents/Repositories/Zelda/ukmm/target/aarch64-apple-darwin/release/deps/libroead-2f56fe14e2ac8b90.rlib(adler32.c.o), archive member 'adler32.c.o' with length 2336 is not mach-o or llvm bitcode file '/Users/neeby/Documents/Repositories/Zelda/ukmm/target/aarch64-apple-darwin/release/deps/libroead-2f56fe14e2ac8b90.rlib' for architecture arm64
          clang: error: linker command failed with exit code 1 (use -v to see invocation)
</pre>
</details>

Implementing the linker flag fix above does cause the `'-Llib/zlib-ng'` warning to go away, but the other error remains.

I can't quite figure out what's causing this, so I'm opening this issue if another contributor has any ideas or suggestions. The release Intel binary works fine using Rosetta, so a universal binary isn't a big issue and just a nice-to-have. Given that the percentage of users on a Mac is likely low, and the number who would care about native binaries is lower still, I'm not sure how much time is actually worth spending on this.

**Comment by neebyA** [comment]
Did some more digging:

```
~> ar -x /Users/neeby/Documents/Repositories/Zelda/ukmm/target/aarch64-apple-darwin/release/deps/libryml-0752d0a56722efa8.rlib
~> file *.o
```
<details>
<summary>Output</summary>
<pre>
684b15975a272bf7-yaz0.rs.o:                          Mach-O 64-bit object arm64
adler32.c.o:                                         Mach-O 64-bit object x86_64
compress.c.o:                                        Mach-O 64-bit object x86_64
crc32.c.o:                                           Mach-O 64-bit object x86_64
crc_folding.c.o:                                     Mach-O 64-bit object x86_64
deflate.c.o:                                         Mach-O 64-bit object x86_64
deflate_fast.c.o:                                    Mach-O 64-bit object x86_64
deflate_medium.c.o:                                  Mach-O 64-bit object x86_64
deflate_quick.c.o:                                   Mach-O 64-bit object x86_64
deflate_slow.c.o:                                    Mach-O 64-bit object x86_64
fill_window_sse.c.o:                                 Mach-O 64-bit object x86_64
functable.c.o:                                       Mach-O 64-bit object x86_64
infback.c.o:                                         Mach-O 64-bit object x86_64
inffast.c.o:                                         Mach-O 64-bit object x86_64
inflate.c.o:                                         Mach-O 64-bit object x86_64
inftrees.c.o:                                        Mach-O 64-bit object x86_64
insert_string_sse.c.o:                               Mach-O 64-bit object x86_64
roead-d885ceb578b186f0.roead.83d5c0b7-cgu.0.rcgu.o:  Mach-O 64-bit object arm64
roead-d885ceb578b186f0.roead.83d5c0b7-cgu.1.rcgu.o:  Mach-O 64-bit object arm64
roead-d885ceb578b186f0.roead.83d5c0b7-cgu.2.rcgu.o:  Mach-O 64-bit object arm64
roead-d885ceb578b186f0.roead.83d5c0b7-cgu.3.rcgu.o:  Mach-O 64-bit object arm64
roead-d885ceb578b186f0.roead.83d5c0b7-cgu.4.rcgu.o:  Mach-O 64-bit object arm64
roead-d885ceb578b186f0.roead.83d5c0b7-cgu.5.rcgu.o:  Mach-O 64-bit object arm64
roead-d885ceb578b186f0.roead.83d5c0b7-cgu.6.rcgu.o:  Mach-O 64-bit object arm64
roead-d885ceb578b186f0.roead.83d5c0b7-cgu.7.rcgu.o:  Mach-O 64-bit object arm64
roead-d885ceb578b186f0.roead.83d5c0b7-cgu.8.rcgu.o:  Mach-O 64-bit object arm64
roead-d885ceb578b186f0.roead.83d5c0b7-cgu.9.rcgu.o:  Mach-O 64-bit object arm64
roead-d885ceb578b186f0.roead.83d5c0b7-cgu.10.rcgu.o: Mach-O 64-bit object arm64
roead-d885ceb578b186f0.roead.83d5c0b7-cgu.11.rcgu.o: Mach-O 64-bit object arm64
roead-d885ceb578b186f0.roead.83d5c0b7-cgu.12.rcgu.o: Mach-O 64-bit object arm64
roead-d885ceb578b186f0.roead.83d5c0b7-cgu.13.rcgu.o: Mach-O 64-bit object arm64
roead-d885ceb578b186f0.roead.83d5c0b7-cgu.14.rcgu.o: Mach-O 64-bit object arm64
roead-d885ceb578b186f0.roead.83d5c0b7-cgu.15.rcgu.o: Mach-O 64-bit object arm64
slide_avx.c.o:                                       Mach-O 64-bit object x86_64
slide_sse.c.o:                                       Mach-O 64-bit object x86_64
trees.c.o:                                           Mach-O 64-bit object x86_64
uncompr.c.o:                                         Mach-O 64-bit object x86_64
x86.c.o:                                             Mach-O 64-bit object x86_64
yaz0.o:                                              Mach-O 64-bit object arm64
zutil.c.o:                                           Mach-O 64-bit object x86_64
</pre>
</details>

It seems the `zlib-ng` objects are not being compiled for the right architecture. I think it might be detecting the architecture of the host rather than the compiler target. There's probably a patch for this upstream, just have to find the right one. Or maybe it would be a `cmake` option?

**Comment by NiceneNerd** [comment]
I have no idea if everything else would work on ARM anyway, but we may as well give it a shot. I have the CI tests running on the roead PR now.

**Comment by neebyA** [comment]
Thanks. I created https://github.com/NiceneNerd/roead/pull/4 to make it possible to build ARM/universal binaries from Intel GitHub runners, in case that's ever something that's wanted

**Comment by neebyA** [comment]
As `bots-utils` is still using `roead 0.20.3`, this issue should be able to be closed as soon as that's updated: https://github.com/NiceneNerd/ukmm/blob/dac2f6336f01370bdebeb3ed67c41d6811474f65/Cargo.lock#L403
