### ISSUE TITLE
Steamdeck Build's UI is many times larger than the deck's screen

### ISSUE THREAD

**Issue by naturalarch3r** [NiceneNerd/ukmm#121]
The steam deck has a screen size of 1280 x 800, but the minimum window size for UKMM appears to be 2552 x 1512. The window can be sized larger, but not smaller than this value. Attempting to use the window manager to force a smaller window causes the window to not render at all.

Having a steamdeck build is pointless if it can't be used on steam deck.

**Comment by NiceneNerd** [comment]
I s'pose the latest workaround didn't automatically work, but the fix for this is still in the docs.
