### ISSUE TITLE
Unusable on Steam Deck (Cannot resize to fit screen)

### ISSUE THREAD

**Issue by z3rglingboss** [NiceneNerd/ukmm#122]
Currently unusable on Steam Deck unless you have a 2nd, large monitor.

UKMM's minimum size is about twice the size of the Steam Deck's 1280x800

**Comment by davdandlv** [comment]
In the meantime, fix is in the docs:
https://nicenenerd.github.io/ukmm/troubleshooting.html

```
This happens on some systems, particularly Steam Deck, for unknown reasons, but can be fixed by setting the environment variable WINIT_X11_SCALE_FACTOR=1.0.
```

**Comment by NiceneNerd** [comment]
Duplicate of several others.
