### ISSUE TITLE
Can't run file 

### ISSUE THREAD

**Issue by Nyessir** [NiceneNerd/ukmm#128]
Can't run ukmm.exe 
It was working for some time but now it won't open when I try.
Not showing me an error when I open or run as admin. When I try to run through command prompt I get 
"thread 'main' panicked at 'no entry found for key', crates\uk-manager\src\mods.rs:206:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
An unrecoverable error occured. Error details: no entry found for key"

**Comment by NiceneNerd** [comment]
Somehow you broke your mod list, not sure how/why. Delete your current profile from `%LOCALAPPDATA%\ukmm\[nx or nx]\profiles\`.
