### ISSUE TITLE
Failed to convert BNP to UKMM Mod

### ISSUE THREAD

**Issue by exedox** [NiceneNerd/ukmm#131]
I'm on my steam deck trying to get the Unofficial Linkle patched bnp to work but I get the following errors:

Failed to convert BNP to UKMM mod

Caused by:
    0: Failed to package converted BNP for mod Unofficial Linkle 3 Patch at `crates/uk-manager/src/bnp.rs@420:6`
    1: No content or DLC folder found in source at /tmp/.tmpOABYgU

I'm not really sure how to get this mod working or if there's something I'm missing.

**Comment by NiceneNerd** [comment]
Since that mod was removed for a rule violation I can't check it out to see what's afoot.

**Comment by exedox** [comment]
They have an updated one here https://gamebanana.com/games/5866

**Comment by exedox** [comment]
> Since that mod was removed for a rule violation I can't check it out to see what's afoot.

They have an updated one here

https://gamebanana.com/games/5866

**Comment by NiceneNerd** [comment]
That's a tool, though, doesn't have an actual mod itself, right?

**Comment by exedox** [comment]
The tool converts the mod to add the assets as a patch for the 3.0mod due to some disagreements with the devs.

**Comment by Lightsockie** [comment]
So I ran the program to try to generate the bnps myself via wine. After unpacking the `thelinklemod301.bnp` and running the program on the resulting directory I get this bnp: [Unofficial_Linkle3_Patch_v21a.bnp](https://files.catbox.moe/xtp5w1.bnp) from the program. When trying to use it with ukmm, I get the error below (verbose on). 
```
[2023-06-04 9:04:53] DEBUG Verbose logging enabled
[2023-06-04 9:04:57] INFO Opening mod at ~/Games/MODS/piiu/botw/bnps/Unofficial_Linkle3_Patch_v21a.bnp
[2023-06-04 9:04:57] INFO Extracting BNP…
[2023-06-04 9:04:57] INFO Processing BNP logs…
[2023-06-04 9:04:57] INFO BNP unpacked
[2023-06-04 9:04:57] INFO Attempting to package mod at /tmp/.tmpfNkDKj
[2023-06-04 9:04:57] DEBUG Using providing meta info:
Meta {
    api: "0.10.0",
    name: "Unofficial Linkle 3 Patch",
    version: "2.1.0",
    author: "",
    category: "",
    description: "The unofficial fix for Linkle 3 too long arms, that also allows you to install Linkle 2 mods on Linkle 3 without neck gaps and -optionally- almost no skin texture issues (some mods may still have wrong physics and will require some rework by their authors).",
    platform: Specific(
        Big,
    ),
    url: None,
    options: [
        Multiple(
            MultipleOptionGroup {
                name: "Optional Components",
                description: "Select one or more of these",
                required: false,
                defaults: {
                    "Dummy1",
                    "Dummy2",
                },
                options: [
                    ModOption {
                        name: "[included] ::: LINKLE 3 LONG ARMS FIX",
                        description: "This fix will be installed no matter what. It will reduce Linkle's arm lenght on the base body to match Linkle 2, forcing any armor to adapt to it.",
                        path: "Dummy1",
                        requires: [],
                    },
                    ModOption {
                        name: "[included] ::: COMPATIBILITY WITH LINKLE 2 MODS",
                        description: "This fix will be installed no matter what. It will allow you to install Linkle 2 mods on Linkle 3 without the annoying neck gap.",
                        path: "Dummy2",
                        requires: [],
                    },
                    ModOption {
                        name: "[optional] ::: SKIN TEXTURE FIX FOR LINKLE 2 MODS",
                        description: "This optional feature will change the upper body skin texture on Linkle 3, to allow Linkle 2 mods to use the base body skin without noticeable issues. The only drawback is, Linkle 3 upper base body may appear less detailed.",
                        path: "Textures",
                        requires: [],
                    },
                ],
            },
        ),
    ],
    masters: {},
}
[2023-06-04 9:04:57] ERROR Failed to convert BNP to UKMM mod

Caused by:
    0: Failed to package converted BNP for mod Unofficial Linkle 3 Patch at `crates/uk-manager/src/bnp.rs@419:6`
    1: No content or DLC folder found in source at /tmp/.tmpfNkDKj

```
(The archive is kinda weird, I think, and uses `\` for directories (prolly cuz of wine). Tried to fix that by unpacking and repacking the archive, mite b useful: [Unofficial_Linkle3_Patch_v21a.bnp-fixedpaths.bnp](https://files.catbox.moe/03grh0.bnp) -- didn't help me tho lol)

re: `: No content or DLC folder found in source at /tmp/.tmpfNkDKj` specifically, I've noticed from other issues that this happens cuz the DLC dir is a bit of a "gotch ya" in that it's different. I make sure I'm pointing to the `content/0010/` subdir (to get ahead of that potential question)

Hopin' this helps to get to the bottom of the issue, and also that maybe we can reopen this issue and give it a less useless title? :^^)
