### ISSUE TITLE
Official DLC actor placement conflicts with UKMM output actor placement

### ISSUE THREAD

**Issue by lisa-wolfgang** [NiceneNerd/ukmm#138]
Certain actors placed by the official DLC don't spawn when the UKMM output replaces the files defining their placement.
For example, the Sheikah Slate terminal in the Shrine of Resurrection does not load in the form that prompts for the player to activate it when the Champion's Ballad quest is triggered. Loading the save with the UKMM graphic pack disabled (or with `content/Pack/TitleBG.pack/Map/MainField/D-6` and `aoc/0010/Map/MainField/D-6` removed before building with Hyrule Builder, then packaging and merging with UKMM) causes the correct form of the Sheikah Slate terminal to load.

What's interesting is that this behavior isn't consistent across all actors. For certain types of actors, the actor simply doesn't spawn in, but others are completely unaffected.
For example, after obtaining the One-Hit Obliterator and re-enabling the UKMM graphic pack or modded map files, when traveling to the Forest of Spirits, all of the added crates, barricades, and chests are there, but none of the enemies spawn in. The trial's blue-green environmental effect and labyrinth music are also missing. The nearby Stone Talus and monster camp are temporarily removed as normal, though.

In addition, when the mod merely modifies the properties of an actor placed by the official DLC, those modifications are completely ignored, and the official DLC version is what ends up in the output graphic pack.
<details><summary><i>Example contains spoiler for the Second Wind mod. Click to show.</i></summary>
<p>
For example, the chest containing Majora's Mask is modified by Second Wind to contain a Green Rupee instead. However, the UKMM output graphic pack does not respect this change: the chest contains Majora's Mask still (the official DLC's property setting for the chest) and not the Green Rupee as specified by Second Wind.
</p>
</details> 

None of the given examples occur on the latest version of BCML, so this is not an issue with the mod I tested (Second Wind, latest development version).

**Comment by lisa-wolfgang** [comment]
I've been testing the latest commit in the Second Wind GitHub repository using `hyrule-builder` to generate a build. That being said, the Great Plateau and the quests provided as examples haven't been modified by Second Wind since the last public release, so the unofficial UKMM port should be able to replicate this issue as well.

**Comment by NiceneNerd** [comment]
The unofficial UKMM port doesn't work on 0.10.0. Also, did you have a bunch of errors trying to build it with Hyrule Builder? I tried doing the same as you but kept hitting error after error. Not sure if I broke Hyrule Builder at some point or what.

**Comment by lisa-wolfgang** [comment]
That's odd. I'm using Hyrule Builder v0.9.0 and don't have to do anything special to get it working.

**Comment by lisa-wolfgang** [comment]
A team member reports that the chest involved with the quest provided as an example in the original post is still exhibiting the same behavior on the latest release of UKMM.
