### ISSUE TITLE
How do I install mods from Gamebanana?

### ISSUE THREAD

**Issue by LaykaKiro** [NiceneNerd/ukmm#14]
It comes up saying this when I select the dumps as the guide said. I may just be doing it wrong so can someone tell me what I did wrong? I used Wii U Helper to dump the games because I don't know how else to do it.
Missing required DLC folder in game dump
(Using ROM at D:\Users\name\path\path\USBHelper Downloads\DL-Dec\The Legend of Zelda Breath of the Wild (DLC) (2.182 GB) (USA) (unpacked)\content) (edited for reasons)

**Comment by LaykaKiro** [comment]
I did it?

**Comment by LaykaKiro** [comment]
I changed the title because I have a new problem. The files seem not to be compatible with UKMM...

**Comment by HGStone** [comment]
first of all.. you illegally obtained the game, please dump it yourself if you wish to receive any help.

https://zeldamods.org/wiki/Help:Dumping_games 

also, no. BNP files are not yet supported

**Comment by LaykaKiro** [comment]
I had no clue how to dump games from my WiiU, so I appreciate the guide.
I also happen to own the game, I just didn't know what I was doing with that stuff so I accepted the alternative.
