### ISSUE TITLE
corrupted linkle textures dont work

### ISSUE THREAD

**Issue by AnityEx** [NiceneNerd/ukmm#141]
the whole linkle 3.0 mod is fine, but the corrupted linkle changes the linkle ancient armor and all the textures seem in their rightful place but the way they are shown is just jumbled up  

https://github.com/NiceneNerd/ukmm/assets/61922421/37163dc5-120c-43aa-9d97-79dbfd0398e1

the mod as it should be: https://gamebanana.com/mods/33494
![image](https://github.com/NiceneNerd/ukmm/assets/61922421/d183a068-4552-4945-acc6-7c06b8926ea6)

these mods are the ones i got
![image](https://github.com/NiceneNerd/ukmm/assets/61922421/fe1d4cbe-94be-435a-b2e2-a6287bfe0854)

windows 11
Cemu 2.0 39 experimental
botw 1.5
ukmm 0.10.1

**Comment by NiceneNerd** [comment]
Have you tied any other priority orderings?

**Comment by AnityEx** [comment]
![image](https://github.com/NiceneNerd/ukmm/assets/61922421/fe7cbb55-56bd-4ab5-b3ef-66d6fa2366c3)
i disabled all mods except the one it needs to work, when priority is over the needed mod it just doesn't show in game other than the icons, and when done as i shown it still glitches
