### ISSUE TITLE
UKMM crashes on Startup

### ISSUE THREAD

**Issue by FOSSHipster** [NiceneNerd/ukmm#143]
I managed to open UKMM fine before, but when I tried importing settings from BCML, it didn't work.

Now, UKMM.exe crashes right after I double-click it. I am not sure what is happening.

**Comment by FOSSHipster** [comment]
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Failed to initialize mod manager at `crates\uk-manager\src\core.rs@21:44`

Caused by:
    0: Failed to parse profile data at `crates\uk-manager\src\mods.rs@278:60`
    1: missing field `mods`', src\gui.rs:290:45
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
An unrecoverable error occured. Error details: called `Result::unwrap()` on an `Err` value: Failed to initialize mod manager at `crates\uk-manager\src\core.rs@21:44`

Caused by:
    0: Failed to parse profile data at `crates\uk-manager\src\mods.rs@278:60`
    1: missing field `mods`

**Comment by NiceneNerd** [comment]
Yeah, somehow your profile is broken. Delete the above-mentioned data, trying the local app data first.

**Comment by FOSSHipster** [comment]
I deleted both folders. It starts up now. Thank you.
