### ISSUE TITLE
Extracting mod and then reinstalling it makes changes

### ISSUE THREAD

**Issue by OsoaGH** [NiceneNerd/ukmm#144]
I extracted Hyrule Rebalance, and then packaged and installed that extracted version (didn't make any changes), and the changes to Link's movements speed in the mod were gone. This makes it difficult to make edits to files such as sbyml, as they are in a strange format in .bnp files and are in UKMM's format when not extracted.

**Comment by OsoaGH** [comment]
I extracted the mod, and then simply repackaged and installed the zip produced. Didn't worry about optional components (not certain how to set that up)

**Comment by NiceneNerd** [comment]
Almost all (or all?) of Hyrule Rebalance's features are optional components

**Comment by OsoaGH** [comment]
I know but it seems when extracting a mod, UKMM merges together extracts only the options you have chosen. I've managed to do the thing I originally wanted to do when I encountered this, so I'm happy to close it, just was worried that it may indicate some inaccuracy with the extraction / merging process
