### ISSUE TITLE
Weapons, shields and bows not upgrade at high scale score

### ISSUE THREAD

**Issue by dhlsc** [NiceneNerd/ukmm#157]
I just migrated from BCML to UKMM by removing and reinstalling all mods, I found that all the weapons, shields and bows that should upgrade as scale score getting higher stayed as they were at start game, e.g., some Savage Lynel still held Lynel Sword with no bonus.
I had tried to install only single mod with several mods, the problem still exists.
When I changed back to BCML, everything went well.
BTW, I use CEMU on a win11 PC.

**Comment by Aeris1One** [comment]
Can you list which mods you are using ?

**Comment by dhlsc** [comment]
Thank you for your reply!
I am using the mods below.

Graphic packs:
* ArmorLimit : https://gamebanana.com/mods/49882

Mods:
* Linkle Mod :  https://gamebanana.com/mods/168235
* Improved Invisible Sheikah Slate : https://gamebanana.com/mods/435061
* Invisible Quiver : https://gamebanana.com/mods/437296
* Zelda Champion Triforce : https://gamebanana.com/mods/321669
* Zelda Travel Dress & Hair for Linkle : https://gamebanana.com/mods/403009

The mods are also sorted as listed from low to high priority.

> Can you list which mods you are using ?
