### ISSUE TITLE
Failed to convert BNP to UKMM mod (probably you saw this too many times, and im sorry)

### ISSUE THREAD

**Issue by Nestea0000** [NiceneNerd/ukmm#162]
So im trying to download this mod:
[https://gamebanana.com/mods/464356](url)
and when trying to convert it it says this:
Failed to convert BNP to UKMM mod

Caused by:
    0: Failed to unpack championsleathers_5fe21.bnp at `crates\uk-manager\src\bnp.rs@399:42`
    1: No config for current platform at `crates\uk-manager\src\bnp.rs@383:14`
can i get some help please?

**Comment by NiceneNerd** [comment]
If it says "no config for current platform," then you should configure your settings

**Comment by thanone2** [comment]
how does one configure their settings?
