### ISSUE TITLE
More detailed "how-to" fix for Steam Deck display scaling issue

### ISSUE THREAD

**Issue by sabre230** [NiceneNerd/ukmm#163]
Currently the help documentation just says to change an environmental variable, but many Steam Deck users don't actually know how to do something like that, let alone for a single application and they will just give up on the software.

The way I've been able to use it comfortably on Steam Deck is to create a Shell script called `ukmm.sh`, place it in the same directory as the `ukmm` application, then putting the following contents inside:

> `#!/bin/sh`
> `WINIT_X11_SCALE_FACTOR=1.0 ./ukmm`

Open the script properties, go to the Permissions tab, and check the box to make the script executable.
Once that is done, UKMM can be opened with the correct window scaling by running `ukmm.sh`.

From there you can add it to Steam as a non-Steam application if you want access to it from game mode.

**Comment by NiceneNerd** [comment]
Addressed in 6d70446.

**Comment by thanone2** [comment]
thx man, you made my life, SO much easier!
