### ISSUE TITLE
Failed to Convert BNP to UKMM Mod

### ISSUE THREAD

**Issue by Snaxolotl71** [NiceneNerd/UKMM#164]
When trying to install [This mod,](https://gamebanana.com/mods/437324), I receive the following error: 

Failed to convert BNP to UKMM mod

Caused by:
    0: Failed to unpack betterelementalallweapons.bnp at `crates\uk-manager\src\bnp.rs@399:42`
    1: Failed to process deepmerge log at `crates\uk-manager\src\bnp.rs@284:14`
    2: Failed to open or create SARC at C:\Users\Gabe\AppData\Local\Temp\.tmpciLiTE\content/Actor/Pack/Weapon_Sword_061.sbactorpack
    3: Failed to get base game SARC at content/Actor/Pack/Weapon_Sword_061.sbactorpack at `crates\uk-manager\src\bnp.rs@192:18`
    4: File not found in game dump: content/Actor/Pack/Weapon_Sword_061.sbactorpack
       (Using source at C:\Users\Gabe\AppData\Roaming\yuzu\dump\BOTW DLC 1\romfs)

Is this a problem with my dump, the mod, or something else?

**Comment by NiceneNerd** [comment]
Are you trying to install a Wii U mod for the Switch game? Paths that start with `content` should be Wii U version, but your dumpl appears to be Switch.

**Comment by Snaxolotl71** [comment]
It looks like that's the case. Is there any way for me to convert it to Switch?
