### ISSUE TITLE
Cant add mod

### ISSUE THREAD

**Issue by BigB-man** [NiceneNerd/UKMM#165]
I tried to add [mod](https://gamebanana.com/mods/453951)

Error:
Failed to convert BNP to UKMM mod

Caused by:
    0: Failed to unpack zonaigun-artemis.bnp at `crates\uk-manager\src\bnp.rs@399:42`
    1: Failed to process maps log at `crates\uk-manager\src\bnp.rs@294:28`
    2: File not found in game dump: Pack/AocMainField.pack

(Using source at D:\wiiu)

**Comment by NiceneNerd** [comment]
Do other mods in general work?

**Comment by ballslover4** [comment]
I am also having the same issues trying to install a mod, here are the causes UKMM lists out: 


Caused by:
    0: Failed to unpack asurasetbalanced.bnp at `crates\uk-manager\src\bnp.rs@399:42`
    1: Failed to process texts log at `crates\uk-manager\src\bnp.rs@304:29`
    2: Failed to read Message/Msg_USen.product.sarc from SARC at path Pack/Bootup_USen.pack//Message/Msg_USen.product.ssarc at `crates\uk-reader\src\lib.rs@281:14`
    3: Failed to get parent for nested file at Pack/Bootup_USen.pack//Message/Msg_USen.product.ssarc at `crates\uk-reader\src\lib.rs@241:74`
    
    
 
 What does this mean? I can't install the zip version of the mod either because it gives me another error saying that mod meta file is missing. How should I go about installing this mod?

**Comment by BigB-man** [comment]
other mods seem to work. 
the only mod that doesn't is second wind:
https://github.com/CEObrainz/Second-Wind/releases/tag/v1.9.14-alpha-3

**Comment by NiceneNerd** [comment]
I think both of your issues should be solved by the last couple of commits.
