### ISSUE TITLE
We need to be able to merge the ShopGameDataInfo.sbym file in the Bootup.pack

### ISSUE THREAD

**Issue by Snarkyfork** [NiceneNerd/UKMM#167]
[Alternate Town Shops](https://gamebanana.com/mods/508547) makes changes to the ShopGameDataInfo.sbyml file in the Bootup.pack to add save flags for shops and no current mod manager (UKMM or BCML) will properly merge this file with other mods that change it. So far its just mods like Relics of the Past, Hyrule Rebalance, etc that make changes to this file but it would be nice to be able to merge it properly. 

I'm not sure about the files located in the savedataformat.ssarc and gamedata.ssarc but those would needed to in order to complete merging of save flags in mods.

**Comment by NiceneNerd** [comment]
UKMM does include a `ShopGameDataInfo` merger, to be found [here](https://github.com/NiceneNerd/UKMM/blob/master/crates/uk-content/src/data/shop.rs). Does using UKMM do nothing at _all_ when multiple mods edit it? What are the results? Can you upload perhaps files for comparison (e.g. the `ShopGameDataInfo.sbyml` from mod A, mod B, and the merged result)?

**Comment by Snarkyfork** [comment]
I was reporting this from someone else who commented about it on GameBanana. It's difficult for me to test myself because I don't normally use the mods (Hyrule Rebalance and RotP are two that I know of) that change that file and I'm familiar with them enough to test it thoroughly. Go ahead and close this if you want and I'll do my best to test it. If I find any evidence of it not working I'll open a new issue, if thats ok.

**Comment by Snarkyfork** [comment]
I was trying to playtest a couple of mods to make sure UKMM was merging the shopgamedatainfo.sbyml files correctly but it seems that the changes made to the on-display items for shops in the [Quality of Life Alternate Shops](https://gamebanana.com/mods/508547) mod aren't showing up in game at all. Does UKMM properly merge mainfield map data yet?

**Comment by NiceneNerd** [comment]
It should be merging maps fine in general, but if the mod uses options, I recently discovered some rather serious issues with how options are handled when installing BNPs, so perhaps that's the issue?

**Comment by Snarkyfork** [comment]
I tried building the quality of life alternate shops mod without options using UKMM so that it wasn't in .bnp format and the changes to shops on-display items still don't seem to work.

**Comment by NiceneNerd** [comment]
So I just tried installing the BNP using a build from the latest commit, and it seems to be working now. I compared what I saw in shops with the screenshots on the mod page and they matched. I'll be uploading a new release soon, let me know if any further trouble emerges.
