### ISSUE TITLE
Dump path settings are not updated properly in config file

### ISSUE THREAD

**Issue by lisa-wolfgang** [NiceneNerd/UKMM#170]
When changing the dump paths through the settings tab, the changes are not written to `settings.yml` (and as a result, not reflected during the merge process.) However, upon exiting the application, the *old values* are written to the file instead of the values the user just entered. Editing the file directly with a text editor is reflected properly in the settings tab and the merge process.

I'm running the latest commit available ([`a188897`](https://github.com/NiceneNerd/UKMM/commit/a188897e35193e0384b26fcbc0fb688ab01880ca)) built on Ubuntu 23.10.

**Comment by NiceneNerd** [comment]
Does the button to save new settings not do anything? Does it pop up the "Settings saved" toast?

**Comment by lisa-wolfgang** [comment]
I see that [here](https://github.com/NiceneNerd/UKMM/blob/master/src/gui/settings.rs#L444) there's a row at the top of the settings page that's supposed to appear with save and reset buttons, but no such row actually appears in the GUI, even after changing the dump settings.

**Comment by NiceneNerd** [comment]
I can't reproduce this thus far. Is it the save button at the bottom or the top of the settings page? Are both working the same way?

**Comment by lisa-wolfgang** [comment]
Both the top and bottom buttons are affected in the same way.

**Comment by NiceneNerd** [comment]
Any chance you could screen record this?
