### ISSUE TITLE
Error Message when closing the app (might be an accidental repeat, delete the other one) 

### ISSUE THREAD

**Issue by SolariaStarz** [NiceneNerd/UKMM#172]
I got a very strange error message written in Chinese when I closed the app and am VERY concerned.. it roughly translated to:  To control the victory, hold the land of Kuifang, respect the animals, smash the desert, pull up, respect and filth,
save the money, and scare the mouth. The wall stimulates the cold town and loses: the desert is satisfied, the wall
cake is barren, the enemy is polluted, and the enemy is lame lingering Rsupports the animal wall and Gukou (row/oar) grilled
The whole thing is fullThe disaster is late, Dunluan is chatting,
the badger is in trouble, the badger is crying, the mule is in bloom, the chestnut is in the chestnut
tree, the chestnut is in the hawthorn field, and the beast is in the water.

![image](https://github.com/NiceneNerd/UKMM/assets/110697659/16d60717-85df-48df-b168-5a2d9018bd7a)

**Comment by SolariaStarz** [comment]
I was able to translate the title, it roughly comes to Fugu Juanzhie

**Comment by NiceneNerd** [comment]
I have no idea what that is

**Comment by davidzchen** [comment]
I think this should be reopened. I got the same issue. Is nobody else experiencing this?
