### ISSUE TITLE
UKMM code not showing in Cemu Appimage graphics pack list.

### ISSUE THREAD

**Issue by Omnicastus** [NiceneNerd/UKMM#177]
On the Steam Deck, I switched from the Proton version to the Appimage version due to a recent update with Emudeck but the UKMM code to activate mods is not appearing in the BotW graphics pack list. I've also been having a lot of odd issues with the Steam Deck version with UKMM, including certain .bnp mods not converting on the SD but converting just fine on Windows.

**Comment by NiceneNerd** [comment]
Immutable systems and AppImages and the like can add up to some funny permissions issues. Does the UKMM folder get created in Cemu's graphic packs folder at all? Also, what are the deployment settings?
