### ISSUE TITLE
Bootup.pack causes crashing

### ISSUE THREAD

**Issue by Thedeadmemelord** [NiceneNerd/UKMM#179]
Pretty self-explanatory, whenever bootup.pack is created by UKMM it causes CEMU to crash.
There is no error message, and it launches just fine when bootup.pack is gone (albeit completely unplayable as it's a very important file).
This happens regardless of what mods I'm using as long as any are enabled. 
I have redumped the game multiple times.

**Comment by NiceneNerd** [comment]
I haven't been able to reproduce this. Can I see your dump settings?

**Comment by Thedeadmemelord** [comment]
![Screenshot 2024-07-24 182804](https://github.com/user-attachments/assets/54944b89-6204-45ab-8207-d8dbe4bd0683)
Sorry, I forgot to do this!

**Comment by Thedeadmemelord** [comment]
As far as I can tell it's a good dump and the settings file is set up correctly.
