### ISSUE TITLE
UI oversized on Steam Deck (linux)

### ISSUE THREAD

**Issue by Skellybob56** [NiceneNerd/ukmm#18]
The text and UI are so over sized it's almost completely unusable.

**Comment by NiceneNerd** [comment]
Try setting the environment variable `WINIT_X11_SCALE_FACTOR=1.0`

**Comment by Skellybob56** [comment]
If you don't mind me asking, how do you do this? I couldn't find any useful information online as  the command `export WINIT_X11_SCALE_FACTOR=1.0`, didn't work.

**Comment by NiceneNerd** [comment]
Didn't work as in it had no discernible effect or it gave an error?

**Comment by Skellybob56** [comment]
No discernible effect, it just replied: `WINIT_X11_SCALE_FACTOR`

**Comment by NiceneNerd** [comment]
Try running with `WINIT_X11_SCALE_FACTOR=1.0 ukmm` to be sure

**Comment by Skellybob56** [comment]
I tried `export WINIT_X11_SCALE_FACTOR=1.0 ukmm`, but It still had no effect, this time the Konsole did not respond at all.

**Comment by NiceneNerd** [comment]
Not `export WINIT_X11_SCALE_FACTOR=1.0 ukmm`, just `WINIT_X11_SCALE_FACTOR=1.0 ukmm` (or maybe (`env WINIT_X11_SCALE_FACTOR=1.0 ukmm`).

**Comment by Skellybob56** [comment]
`WINIT_X11_SCALE_FACTOR=1.0 ukmm` returned `bash: ukmm: command not found`
`env WINIT_X11_SCALE_FACTOR=1.0 ukmm` returned `env: 'ukmm': No such file or directory`

**Comment by Skellybob56** [comment]
I also tried `WINIT_X11_SCALE_FACTOR=1.0` - with no response or effect

**Comment by NiceneNerd** [comment]
Oops, that should have been `env WINIT_X11_SCALE_FACTOR=1.0 ./ukmm` (or whatever the path to the UKMM executable is in your case)

**Comment by Skellybob56** [comment]
That worked. Thankypu so much for making UKMM and BCML and for spending time trying to fix my problem! Sorry for my lack of linux knowledge btw, I'm mostly a windows user.
