### ISSUE TITLE
Issue where certain mods won't load on UKMM

### ISSUE THREAD

**Issue by rexterjettster** [NiceneNerd/UKMM#180]
I'm not that tech savvy when it comes to modding BOTW and someone who was helping me through this said that I should report this issue. I'm trying to upload a mod named Mipha's Grace to my UKMM, and I'm unable to get it to load in despite having everything I need set up already. 
![image (2)](https://github.com/NiceneNerd/UKMM/assets/174167000/0fa65b26-2ce8-489a-b79a-7c0d3a141ce3)
I have no clue what any of this means, but I've also been suggested to try using BCML to run this mod so I'm going to try that as well for my own convenience. It just won't load on UKMM, other mods will though, like QNando's Zelda mod. Any help would be amazing, I'm dying to try and play this mod properly.

**Comment by NiceneNerd** [comment]
Seems like the mod has at least one corrupt file.

**Comment by rexterjettster** [comment]
> Seems like the mod has at least one corrupt file.

The mod loaded up in BCML and works on the Wii U, so this is probably not the issue.

**Comment by NiceneNerd** [comment]
Eh, BCML and BOTW both often ignore corrupted files in silence when possible.

**Comment by rexterjettster** [comment]
That'd make sense. Thank you anyways. Hopefully the mod maker has it
resolved by the time it is published.
