### ISSUE TITLE
Fail to convert Mod

### ISSUE THREAD

**Issue by xXDarkNovaXx** [NiceneNerd/UKMM#183]
Failed to convert BNP to UKMM mod

Caused by:
    0: Failed to unpack Unofficial_Linkle3_Patch_v21a.bnp at `crates\uk-manager\src\bnp.rs@520:42`
    1: Failed to extract BNP at `crates\uk-manager\src\bnp.rs@486:36`
    2: BadSignature([80, 75, 3, 4, 20, 0])
    
    
This bnp was created with the patcher tool of the mod.
To be able to reproduce the problem I have attached a zip with the .bnp: [Unofficial_Linkle3_Patch_v21a.zip](https://github.com/user-attachments/files/16101853/Unofficial_Linkle3_Patch_v21a.zip)
|
|
|
|
|   
However, you can install the mod via a workaround if you first install the mod in BCML and then use the migrate function of U-King Mod Manger to add the mod in the Mod Manager.

During the migration the textures are not migrated you have to copy the folder Model and Pack from the texture folder of the bnp and then add it in the Linkle Patch Zip in the mod folder of the mod manager in the folder Options/Textures itself and then add these two folders in the manifest.yml.

I made 2 screenshots of what it should look like in the zip if you add the textures yourself: 
![Screenshot_fix_1](https://github.com/NiceneNerd/UKMM/assets/22129313/606090cf-3ba2-4628-833d-f352eeceda91)
![Screenshot_fix_2](https://github.com/NiceneNerd/UKMM/assets/22129313/15e72fad-5552-46e9-a79e-e59a707df688)

**Comment by NiceneNerd** [comment]
The BNP seems to be broken. As far as I can tell, it's not really a 7z archive but a ZIP with the inner file paths stored incorrectly.

**Comment by xXDarkNovaXx** [comment]
> The BNP seems to be broken. As far as I can tell, it's not really a 7z archive but a ZIP with the inner file paths stored incorrectly.

If the BNP looks like it's broken, I wonder why the mod always worked with BCML
Then I'll probably have to continue installing the mod via my workaround in case I have to reinstall it at some point

**Comment by NiceneNerd** [comment]
Different extractors have different ways of handling archives that don't match expectations. You *might* be able to get UKMM to use it by switching your Use System 7z setting. Alternatively, and more easily, the mod could simply be extracted and then correctly repackaged with 7-Zip.

**Comment by xXDarkNovaXx** [comment]
> Different extractors have different ways of handling archives that don't match expectations. You _might_ be able to get UKMM to use it by switching your Use System 7z setting. Alternatively, and more easily, the mod could simply be extracted and then correctly repackaged with 7-Zip.

Newly packaged, it seems to work
I could imagine that the patcher packs the zip in such a way that the mod manager has problems with it because the patcher is already a few years old

When converting, data seems to be moved and renamed, do you have to adapt the Manifest.yml to the changes or is it no longer needed with U-King Mod Manager and can be ignored?
