### ISSUE TITLE
Unable to install MOD files with non-English names

### ISSUE THREAD

**Issue by KH-Ann** [NiceneNerd/UKMM#184]
![QQ截图20240708020016](https://github.com/NiceneNerd/UKMM/assets/58108238/01b64d10-1bfa-465b-ad58-6610b468309c)
Using non-English files will cause the installation to fail and the characters cannot be displayed correctly.

**Comment by NiceneNerd** [comment]
According to the error logs in your screenshot, the problem is not the non-English characters but the file format, which is ZIP rather than 7z.

**Comment by KH-Ann** [comment]
![QQ截图20240708032632](https://github.com/NiceneNerd/UKMM/assets/58108238/889ae01b-8efe-4c30-a378-d737c2e524cb)
When UKMM and BCML install the same MOD, Chinese cannot be displayed correctly.

**Comment by KH-Ann** [comment]
Can I contact you using discord? I found a new bug that causes the program to crash. Sorry, my English is not good, I use Google Translate

**Comment by NiceneNerd** [comment]
If it makes the program crash, go ahead and make a new isue.

As for the Chinese characters, that has to do with how egui handles fonts, and I am unsure what I want to do about it.
