### ISSUE TITLE
bnp always fails

### ISSUE THREAD

**Issue by Scrappythethird** [NiceneNerd/UKMM#185]
![Image 07-07-2024 at 23 21](https://github.com/NiceneNerd/UKMM/assets/174963698/235593dd-b1da-42e6-a8ab-0b6ed58c473b)

**Comment by NiceneNerd** [comment]
I can't seem to replicate this with the mod in your screenshot. Are you sure your game dump settings are sound?

**Comment by Scrappythethird** [comment]
look
![Image 07-07-2024 at 23 49](https://github.com/NiceneNerd/UKMM/assets/174963698/bf0ac42a-c913-4e60-9247-cf1751f870e8)

**Comment by Scrappythethird** [comment]
WARN]: Could not load pending deployment data:
failed to open file `/Users/umbreenamanullah/Library/Application Support/ukmm/wiiu/pending.yml`
is this what's wrong?

**Comment by NiceneNerd** [comment]
That warning doesn't really matter.

Without seeing what's in those folders, though, it's hard to guess whether the dump is good or not.

**Comment by Scrappythethird** [comment]
what folders?

**Comment by NiceneNerd** [comment]
The game dump folders you specified

**Comment by Scrappythethird** [comment]
how do i know if it is a good dump?

**Comment by NiceneNerd** [comment]
The basics are [here](https://nicenenerd.github.io/UKMM/setup/dump-settings.html)

**Comment by Scrappythethird** [comment]
yup good dumps

**Comment by NiceneNerd** [comment]
Post your full settings file (at `%APPDATA%\ukmm\settings.yml` or `%LOCALAPPDATA%\ukmm\settings.yml`)

**Comment by Scrappythethird** [comment]
im on a mac

**Comment by Scrappythethird** [comment]
i can't

**Comment by Scrappythethird** [comment]
[profile.yml.zip](https://github.com/user-attachments/files/16120739/profile.yml.zip)
try this

**Comment by Scrappythethird** [comment]
current_mode: WiiU
system_7z: true
storage_dir: /Users/umbreenamanullah/Library/Application Support/ukmm
check_updates: Stable
show_changelog: true
last_version: 0.12.0
wiiu_config:
  language: USen
  profile: Default
  dump:
    bin_type: Nintendo
    source:
      type: Unpacked
      host_path: /Users/umbreenamanullah/Downloads/usr/title
      content_dir: /Users/umbreenamanullah/Downloads/usr/title/00050000/101c9400/content
      update_dir: /Users/umbreenamanullah/Downloads/usr/title/0005000e
      aoc_dir: /Users/umbreenamanullah/Downloads/usr/title/0005000c
  deploy_config:
    output: /Users/umbreenamanullah/Library/Application Support/Cemu/graphicPacks/BreathOfTheWild_UKMM.
    method: HardLink
    auto: true
    cemu_rules: true
    executable: /Applications/Cemu.app
switch_config: null

**Comment by NiceneNerd** [comment]
Your update and DLC folders appear to be incorrect. Double check the instructions linked above.

**Comment by Scrappythethird** [comment]
current_mode: WiiU
system_7z: true
storage_dir: /Users/umbreenamanullah/Library/Application Support/ukmm
check_updates: Stable
show_changelog: true
last_version: 0.12.0
wiiu_config:
  language: USen
  profile: Default
  dump:
    bin_type: Nintendo
    source:
      type: Unpacked
      host_path: /Users/umbreenamanullah/Library/Application Support/Cemu/mlc01/usr/title
      content_dir: /Users/umbreenamanullah/Library/Application Support/Cemu/mlc01/usr/title/00050000/101c9400/content
      update_dir: /Users/umbreenamanullah/Library/Application Support/Cemu/mlc01/usr/title/0005000e/101c9400/content
      aoc_dir: /Users/umbreenamanullah/Library/Application Support/Cemu/mlc01/usr/title/0005000c/content/0010
  deploy_config:
    output: /Users/umbreenamanullah/Library/Application Support/Cemu/graphicPacks/BreathOfTheWild_UKMM.
    method: HardLink
    auto: true
    cemu_rules: true
    executable: /Applications/Cemu.app
switch_config: null

**Comment by Scrappythethird** [comment]
https://gamebanana.com/mods/471343 here's the link to the mod btw

**Comment by NiceneNerd** [comment]
With the corrected dump settings, restart UKMM to be safe, and it should work, unless you get an unrelated error.

**Comment by Scrappythethird** [comment]
![Image 08-07-2024 at 01 47](https://github.com/NiceneNerd/UKMM/assets/174963698/52e56bf0-2335-4fb1-8b9d-33412f300237)

this error

**Comment by Scrappythethird** [comment]
same error

**Comment by Scrappythethird** [comment]
nope

**Comment by NiceneNerd** [comment]
Then something is indeed wrong with your dump

**Comment by Scrappythethird** [comment]
well i give up thx for your help anyway

**Comment by NiceneNerd** [comment]
I would go back through a dumping guide and pay careful attention to where everything goes

**Comment by Scrappythethird** [comment]
doublechecked it exists

**Comment by QuantumSpaceToaster** [comment]
I'm getting the same issue, looked over the entire guide multiple times, and triple checked that I dumped the game correctly and I did.

**Comment by NiceneNerd** [comment]
Same exact error text with the same mod?

**Comment by QuantumSpaceToaster** [comment]
It's a very similar error message, but not the same mod.

0. Failed to convert BNP to UKMM mod
1. Failed to unpack Second Wind 1.9.14-alpha-4.bnp at `crates\uk-manager\src\bnp.rs@520:42`
2. Failed to process texts log at `crates\uk-manager\src\bnp.rs@421:29`
3. missing field `type` at line 4919 column 10

Thanks for replying so fast.

**Comment by NiceneNerd** [comment]
Ah, that error is entirely unrelated, and was fixed in a recent commit, so it will be solved in the next release.

**Comment by QuantumSpaceToaster** [comment]
Nice! When do you think it will release?

**Comment by GingerAvalanche** [comment]
Seems like any issues here have all been solved and this one can be closed.
