### ISSUE TITLE
Creating new profile in UKMM causes crash

### ISSUE THREAD

**Issue by KH-Ann** [NiceneNerd/UKMM#186]
![1](https://github.com/NiceneNerd/UKMM/assets/58108238/192bae68-ab8b-49dc-a98d-9be3bfdee1da)
![2](https://github.com/NiceneNerd/UKMM/assets/58108238/bdddbc8d-a365-45cc-80d0-af7e30cc00df)
But I didn't put in any names and he crashed.

**Comment by NiceneNerd** [comment]
Does it crash if you *do* put in a name?

**Comment by KH-Ann** [comment]
> Does it crash if you _do_ put in a name?

It won't
