### ISSUE TITLE
New paths in latest Cemu versions

### ISSUE THREAD

**Issue by JaimieVandenbergh** [NiceneNerd/UKMM#192]
Hi! Cemu 2.0 has new path locations and logic in recent versions (current is -91), which you should be aware of as the ukmm settings path logic will probably get upset. Obviously applies to BCML as well.

This applies to `settings.xml`, default `mlc01`, `graphicPacks` as well as other less relevant stuff. Not `Cemu.exe` which lives wherever the user unzips it to.

The new setup works like this on Windows (in this order):

1. If a folder `portable` exists next to `Cemu.exe` it will use it to store all those files
2. If `settings.xml` already exists next to `Cemu.exe` (from e.g. a previous/running installation) it will store files in that same folder, same as previous versions
3. Otherwise it falls back to the new default location of `%appdata%/Cemu`
 
People can check what folder Cemu is using as its root with Cemu's "File" menu, "Open Cemu Folder". (There's a new "Open mlc01 folder" there too)
 
https://discord.com/channels/286429969104764928/292706660877860865/1268128247653208166

Cheers - Jaimie (mod on the Cemu offficial discord)

**Comment by GingerAvalanche** [comment]
Thanks for the heads up, Jaimie!

For the fallback, is that %appdata% the all-user one, e.g. AppData/Roaming on Windows? Or is it %localappdata% the current user one, e.g. AppData/Local on Windows?

I think `settings.xml` is no longer relevant, since there's a `rules.txt` parameter for enabling a graphic pack by default, but the others will be helpful.

**Comment by JaimieVandenbergh** [comment]
It's in Roaming, so eg `C:\Users\jaimie\AppData\Roaming\Cemu\`
Full list of stuff created in it:
```
controllerProfiles/
graphicPacks/ (once the user downloads them)
memorySearcher/
mlc01/
shaderCache/
settings.xml
```

**Comment by GingerAvalanche** [comment]
I just noticed you said “on Windows” it does that. Is there different behavior on Linux/Mac? (Does Cemu even support macOS? I forget)

Might as well nab all the new path behavior in one go.

**Comment by JaimieVandenbergh** [comment]
Linux and Mac already had to deal with separation of binary and data.

Mac defaults to putting all the Cemu folder stuff in `/Users/{username}/Library/Application Support/Cemu/`

I'm not 100% confident on the native Linux config, but at least for the appimage it's `~/.local/share/Cemu/`
