### ISSUE TITLE
Recipe Merging Issues

### ISSUE THREAD

**Issue by GingerAvalanche** [NiceneNerd/UKMM#206]
It's been pointed out to me that recipes can only have a maximum of 3 items. If two mods combine a recipe file to form a merged file with 4 or more items, the game takes whichever first 3 are in the file, based on the order of the merger's iteration.

I don't really know of a good way to fix this. Probably the best way is to not merge recipe files and instead just take the recipe belonging to the highest priority mod.

However, would that be more trouble than it's worth, to remove merging behavior for that file type? Maybe it'd be a better idea to only have the recipe merger merge the highest priority diff?

I'll work on what you think is best @NiceneNerd

**Comment by NiceneNerd** [comment]
Come to think of it, it is probably true that there is almost no way for merging recipes to produce results which are both sane and at all expected. Fully overriding them is probably the best route. 

Specifically, I'd update the merger to just blind clone everything when diffing and leave merging as-is. This should solve the problem on all mods installed hereafter without breaking existing installs any more than they may already be. It will also mean we don't have to specifically add them as a merging exclusion or forget to do that and wind up applying blind AAMP merging.

**Comment by GingerAvalanche** [comment]
What about the case where two mods both add a new item to the list? All properties would become adds, and then the merger would combine all adds into a single file with everything in it, wouldn't it?

**Comment by NiceneNerd** [comment]
Oh, yeah, forgot that one. A dirty fix might be to just cap how many can get merged.

**Comment by GingerAvalanche** [comment]
The game already effectively does that. No matter the ColumnNum, it only reads the first 3. It's just... which 3 are first are semirandom, due to the fact that it's an unordered map that stores the merged diffs when merging.

Kind of a mess all around, really. I can't help but think the *correct* thing is to just remove merging for them altogether, but theoretically we could also find where the diffs are collected before they get merged into the final one, and then drop all but the last one (or first and last, if the vanilla file is the first "diff")
