### ISSUE TITLE
When applying the mod Quality of Life NG+ on Mac, it gives an error.

### ISSUE THREAD

**Issue by 98i87** [NiceneNerd/UKMM#210]
```
Failed to apply pending mod changes

Caused by:
    0: Failed to build SARC file Pack/Bootup.pack at `crates/uk-mod/src/unpack.rs@796:22`
    1: Failed to build file Ecosystem/StatusEffectList.sbyml for SARC at `crates/uk-mod/src/unpack.rs@818:18`
    2: Error deserializing resource Ecosystem/StatusEffectList.byml from mod Quality of Life NG+ v1.0.6. Error: error kind: TypeMismatch{ f32 }, msg: expected array
```
I'm pretty sure this binary I'm using is compiled from source, but maybe some files from the Intel version I used are causing some conflicts? 

(If I click deploy and try use it on Cemu, Cemu crashes after the game opens.)

**Comment by NiceneNerd** [comment]
If you compiled from source recently, there were breaking changes to the `StatusEffectList` internal format that would prevent mods which packaged for UKMM or installed before those changes from working.

**Comment by 98i87** [comment]
Thank you, which release did this happen on, by the way?
