### ISSUE TITLE
Cannot uninstall a mod that was manually deleted from the  \wiiu\mods folder

### ISSUE THREAD

**Issue by fuser-invent** [NiceneNerd/UKMM#213]
Using the newest build "0.15.0 - 2024-08-29" on a Wiindows 11 computer. 

I had a mod installed through UKMM. I deleted the mod's .zip file from the \wiiu\mods folder. The mod remains in the UI mods list. If I try to uninstall the mod, overwrite it with the Update option, or disable it by choosing the Disable option or unchecking the box, I get the following error:

![image](https://github.com/user-attachments/assets/1ca496bc-9417-45a4-9c12-fd6328978577)

I also get this in the Log:

![image](https://github.com/user-attachments/assets/4671adb0-d063-4192-b147-fecefa68ef02)

**Comment by NiceneNerd** [comment]
Manually deleting mods is not supported.

**Comment by fuser-invent** [comment]
Then how do I resolve this? It completely breaks UKMM. I now have several mods, including ones that I didn't manually delete, which will not uninstall and are stuck in the mods list.

Without an option to manually delete them, force remove a broken mod from the mod list, and/or remove it from how UKMM records info for the install, any mod that doesn’t work with UKMM will get stuck in the list and cause file path errors.

The other mods that are now stuck and won’t uninstall are the 3 packages from Quality of Life NG+.

**Comment by NiceneNerd** [comment]
You can either manually edit (to remove entries related to the broken mod(s)) or delete your profile information in `%LOCALAPPDATA%\ukmm\profiles`.

**Comment by fuser-invent** [comment]
The **profile.yml** in the location C:\Users\benja\AppData\Local\ukmm\wiiu\profiles\Default only contains the following and there are no other profile folders in C:\Users\benja\AppData\Local\ukmm\wiiu\profiles\:
```
mods: {}
load_order: []
```
Additionally, that **profile.yml** in the **Default** folder still contains no information, even if mods are installed in the **Default** profile from within UKMM's UI. I have a profile called **BenjaZ** and one called **Test**. The **BenjaZ** profile contains all of my mods and where I initially found the error.

Closing UKMM, deleting **profile.yml**, and opening UKMM again does not remove the stuck mods from the mods list, which is expected because the YAML is empty.

In UKMM's UI, if I  go to **Manage Profiles**  and **Duplicate** the **BenjaZ** profile to **BenjaZ - Copy**, then switch to it, the app crashes and I get this error:

![image](https://github.com/user-attachments/assets/83046b08-c344-4690-b39c-0d3e35104e52)

When I try to open UKMM again, I get this error:

![image](https://github.com/user-attachments/assets/b70ce4bd-7014-4621-b613-f88c7d150e19)

If I go to Z:\Cemu-Emulator\wiiu\profiles (as seen in the error message) and delete Z:\Cemu-Emulator\wiiu\profiles\BenjaZ_copy then Cemu will open again.

I then inspected the YAML at Z:\Cemu-Emulator\wiiu\profiles\BenjaZ which appears to be the correct(?) location profiles are being saved in and confirmed that the file paths do not update if the actual file path is changed and updated in UKMM's settings page, and found the undeletable mods are still in the YAML. Here is a [PasteBin link to the full YAML](https://pastebin.com/11nnqJgE).

I also confirmed that if I delete the entries for the stuck mods in the YAML under **mods:** and **load_order:** they are manually deleted from the Mods list in the UI. These were the stuck mods:

- 8812769242042437620
- 12618802445105307041
- 16293854418153968460
- 15849707435724087480

If a _new mod_ is added to Mods in the UI, it reflects the file path changes in the YAML for that mod. However, with all my testing, now no mods work. That's totally okay with me, just let me know if you want me to check anything else. I have a decent amount of experience in bug testing.

**Comment by GingerAvalanche** [comment]
You're basically just hitting a minefield of a lot of things UKMM doesn't support and/or had bugs with.

- Don't manually edit anything related to UKMM in your AppData. It's unsupported, and you could be doing a whole lot of things we can't account for and can't recover from. If you need to edit something, use the UI
- The missing profile.yml after the duplication was an error with the file copier on Windows. It's minorly documented in #207 and is fixed in #224 and will be rolled into the next version. There's a preview of that version available [here](https://github.com/GingerAvalanche/ukmm/releases/tag/v0.15.0), which includes a changelog of all the differences between it and the official 0.15.0
