### ISSUE TITLE
Second Wind on Steam Deck

### ISSUE THREAD

**Issue by ghost** [NiceneNerd/ukmm#227]
Since version 6 of second wind supposedly doesn't work unless you use a custom build (which needed dependencies I didn't feel like going through), I downloaded alpha 5. But I get this error:
No copy of Actor/AS/DungeonPart_Constant.bas found in game dump or any mod
I have verified my Base and Update files, they are not the problem. However, it is right, I do not see the .bas file mentioned in the update or dlc directories.

**Comment by ghost** [comment]
Oh sorry I meant "I do not see the .bas file in the base or update directories". I do not own the dlc.

**Comment by NiceneNerd** [comment]
You cannot use Second Wind without DLC.
