### ISSUE TITLE
Installing Clear Camera breaks Bootup.pack

### ISSUE THREAD

**Issue by Benna96** [NiceneNerd/ukmm#23]
[Link to the mod](https://gamebanana.com/mods/296638), I used the no detection version.  
The BNP contains `Pack/Bootup.pack`, with its only content being `Layout/Common.sblarc` containing only `blyt/AppCamera_00.bflyt`.  
With BCML, the result is a `Pack/Bootup.pack`, where `Layout/Common.sblarc//blyt/AppCamera_00.bflyt` is the one from the mod, all other files are vanilla.

With UKMM however:
- If installing the BNP, `Bootup.pack//Layout/Common.sblarc` gets replaced with the incomplete one from the BNP; As a result, all the other files that are supposed to be inside the sblarc are no longer there.  
  There's seemingly no merging happening within the sblarc; If there was, the resulting UKMM mod would have a `blyt/AppCamera_00.bflyt` file in addition to the `Layout/Common.blarc` file, correct? It only has the `Pack/Bootup.pack` and `Layout/Common.blarc` files however.   
  The game crashes before getting to the title screen, hardly surprising given there's files missing.
- If converting the BNP to standalone and installing the resulting graphics pack, or alternatively using the result of the standalone with or without the RSTB to package a UKMM mod and installing that... The resulting `Pack/Bootup.pack` looks okay, all the files seem to be there, but the game still doesn't make it to title screen.

**Comment by NiceneNerd** [comment]
So this in part involved me being dumb and skipping a step in BNP SARC inflation. I'll need to double check a little later about the standalone case, though.
