### ISSUE TITLE
Packaging broken for non-cross-platform mods

### ISSUE THREAD

**Issue by Benna96** [NiceneNerd/ukmm#24]
Getting the following error when packaging any mod not marked as cross-platform:
![image](https://user-images.githubusercontent.com/23498000/216838332-d6979e7b-2e99-4fe1-b6a9-8e602e6f26e9.png)

It fails when writing meta.

**Comment by NiceneNerd** [comment]
Hmm, seems this is another case of an annoying limitation of using serde with TOML. As much as I like TOML as a format, the defeat serde settings are rather stunted. S'pose I'll just switch to YAML like I'm already using for other things.
