### ISSUE TITLE
Linkle dialogue nx not installing with ukmm

### ISSUE THREAD

**Issue by Danto003** [NiceneNerd/ukmm#240]
evrytime i try to install the Linkle dialogue nx mod with ukmm, i get this message. i dont know if im doing anything wrong. 

ERROR]: Failed to convert BNP to UKMM mod

Caused by:
    0: Failed to unpack the_legend_of_linkle_dialogue_mod_nx_v118.bnp at `crates\uk-manager\src\bnp.rs@522:42`
    1: Failed to process maps log at `crates\uk-manager\src\bnp.rs@413:28`
    2: File not found in game dump: Pack/AocMainField.pack
       (Using source at C:\Users\larsa\AppData\Roaming\yuzu\dump)

**Comment by Helvetica-St4ndard** [comment]
did you ever solve it?
