### ISSUE TITLE
'None' option added multiple times to optional exclusive option groups

### ISSUE THREAD

**Issue by Benna96** [NiceneNerd/ukmm#28]
Probably supposed to be added once per option group, but it's instead being added once before each individual option.
![image](https://user-images.githubusercontent.com/23498000/218188165-aff0400e-0a39-4235-bcfe-8287d5f1d79a.png)

**Comment by NiceneNerd** [comment]
Fixed in fed06c33f4d36f40ef6f6299c6be4f60e7be7aac.
