### ISSUE TITLE
Option related .pack issue when mod adds new file

### ISSUE THREAD

**Issue by Benna96** [NiceneNerd/ukmm#29]
When the main content of a mod adds a new file to a `.pack` file, and an option modifies something else in the same `.pack` file without including this new file, the new file added in the main content gets removed.  
Happens both with BNPs and when packaging a mod.

I ran into this trying to install [The Linkle Mod 3.0](https://gamebanana.com/mods/406768).  
The mod adds `Model/Linkle_Extra_Animation.sbfres` to `TitleBG.pack`. This file does not exist in vanilla.  
An option of the mod, umbrella glider, doesn't add any new files, just modifies some existing ones.  
![image](https://user-images.githubusercontent.com/23498000/218209529-824346fd-ffd8-4f1d-a500-d2d112f2de91.png)  
Installing the umbrella glider option results in `Model/Linkle_Extra_Animation.sbfres` not being in `TitleBG.pack` (causing infinite loading screen).  
Removing `options/Umbrella Glider/Pack/TitleBG.pack` from the generated mod and installing that instead fixes the issue.

It seems to me as if when generating `TitleBG.pack`, UKMM compares the option .pack to the main .pack, rather than the vanilla .pack which it's actually based on. Perhaps this is desired when manually packaging, maybe someone would want to remove a file when a certain option is selected..? Definitely not when it comes to BNPs though, as BCML doesn't have that functionality to my knowledge.

In my case, I'm guessing the BNP converter first converts the partial .pack files from the BNP into full ones based on vanilla. Then, when generating `TitleBG.pack`, it arrives at "the main .pack has `Model/Linkle_Extra_Animation.sbfres`, but this option one doesn't, so what this option does is remove that file".

Purely a guess, of course.

**Comment by NiceneNerd** [comment]
Your guess was precisely correct. Fixed in fed06c33f4d36f40ef6f6299c6be4f60e7be7aac.
