### ISSUE TITLE
Add support for 1-click BNP

### ISSUE THREAD

**Issue by ramonsantana** [NiceneNerd/ukmm#3]
Any chance of adding support for BCML files?
Reason:  i have a lot of mods installed with it and don't know if they will work, i know of only Second Wind transitioning to this loader

**Comment by NiceneNerd** [comment]
A way to install BNPs is planned, though probably not until closer to 1.0. In the meantime, the roundabout method to install BNPs is to use the "BNP to Standalone" button in BCML, and then install the standalone mod it creates.
