### ISSUE TITLE
Error while opening executable on Steam Deck

### ISSUE THREAD

**Issue by kokomo123** [NiceneNerd/ukmm#30]
OS: SteamOS 3.4.4 
Whenever i run the executable, I get this error: error while loading shared libraries: libssl.so.3: cannot open shared object file: No such file or directory as I believe Steam doesn't install libssl by default, and that would mean turning off the read only filesystem, and getting pacman to install it but it will be wiped upon another update unfortunately.

**Comment by NiceneNerd** [comment]
That's very good to know. I'll see if I can switch it to statically link it.

**Comment by Trikzon** [comment]
I am getting this error on my Steam Deck with v0.13.0
