### ISSUE TITLE
bfevfl files get extracted funny

### ISSUE THREAD

**Issue by DeathWrench** [NiceneNerd/ukmm#31]
If you install a mod (with unpack mods checked) that replaces bfevfl files like [Seamless Warping](https://gamebanana.com/mods/415792) you can't open the bfevfl files with [Event Editor](https://zeldamods.org/wiki/Help:Tools/EventEditor) _and_ you can't replace an installed UKMM mod's bfevfl files made with Event Editor. Upon Deploying after trying this it says:

Failed to apply pending mod changes

Caused by:
    0: Failed to build SARC file Event/Demo202_1.sbeventpack
    1: Failed to build file EventFlow/Demo202_1.bfevfl for SARC
    2: Failed to parse mod resource EventFlow/Demo202_1.bfevfl in mod 'Seamless Trials'
    3: error kind: TypeMismatch{ bytes }, msg: expected map or string

**Comment by NiceneNerd** [comment]
This is the intended behavior. From [the book](https://nicenenerd.github.io/ukmm/mod_format.html#resources):

> All modified files, included nested files stored in SARCs, are stored at their canonical resource paths. **Special note**: *These are not stored as ordinary game files in their original formats.* Rather, UKMM parses most files into diffable, mergeable data structures representing their semantic content, and then stores only the diffs, serialized to [CBOR](https://cbor.io/) using [`minicbor-ser`](https://crates.io/crates/minicbor-ser).
>
> Even files which UKMM cannot parse and merge are still stored with CBOR metadata and thus cannot be used in the game as-is.

**Comment by DeathWrench** [comment]
Is there some sort of way to have the loose source files for specific installed mods in a set directory? UKMM could re-parse these mods files every time without having to re-zip then uninstall and reinstall the mod. For modding purposes this would make things a lot quicker.

**Comment by NiceneNerd** [comment]
There are plans in the works for streamlining the mod development process.
