### ISSUE TITLE
Issue when applying pending mod changes

### ISSUE THREAD

**Issue by Nokta-777** [NiceneNerd/ukmm#33]
For example, when I try to install Linkle mod 3.0, it makes me this error : 

*Failed to apply pending mod changes*

*Caused by:*
    *0: Failed to build SARC file Actor/Pack/Armor_087_Upper.sbactorpack*
    *1: Failed to build file Physics/Cloth/Armor_175/Armor_175_Upper.hkcl for SARC*
    *2: No base version for file Physics/Cloth/Armor_175/Armor_175_Upper.hkcl*

**Comment by NiceneNerd** [comment]
I successfully installed the Linkle mod earlier, are you using Wii U or Switch mode, and are you sure your game dump folders are set correctly?

**Comment by Nokta-777** [comment]
I am using the Wii U mod

And I think my game dump folders are correct, I stopped in "content" for the Base game and the update, and in "0010" for the DLC

**Comment by NiceneNerd** [comment]
What's your update folder set to exactly? Does `[Your update folder]/Actor/Pack/Armor_087_Upper.sbactorpack` exist?

**Comment by Nokta-777** [comment]
Sorry for the time I took to answer.
My update folder on UKMM isn't set as the one in the `mlc01` folder
`Armor_087_Upper.sbactorpack` does exist in this folder (I just re-checked to be sure)

**Comment by NiceneNerd** [comment]
What are the folders set to, then?

**Comment by Nokta-777** [comment]
My update folder is set to `(Path to my BOTW folder)\The Legend of Zelda Breath of the Wild (UPDATE DATA) (v208) (3,253 GB) (EUR) (unpacked)\content` on UKMM

My main game folder is also set to content, and my DLC folder is set to the `0010` folder

**Comment by Dysuria** [comment]
I had the exact same issue and running ukmm.exe as administrator solved it.

**Comment by NiceneNerd** [comment]
I have a strong hunch that was a coincidence

**Comment by Nokta-777** [comment]
Sorry for the time .... (I was busy for a moment)

It seems to work ......... I was pretty sure to have ran it as administrator though .... 


However, thank you all
