### ISSUE TITLE
"Failed to convert BNP to UKKM mod" trying to add mod without Bootup.pack

### ISSUE THREAD

**Issue by RealEmanGaming** [NiceneNerd/ukmm#34]
As the title implies, whenever I try to add a mod that doesn't have a `Pack/Bootup.pack` file, it can't convert it.

Console Log:

    [2023-02-14T07:44:30Z ERROR ukmm::gui] Failed to convert BNP to UKKM mod
    Caused by:
        0: Failed to unpack BNP
        1: Failed to process eventinfo log
        2: failed to create file `C:\Users\User\AppData\Local\Temp\.tmpdObNBA\01007EF00011E000/romfs\Pack/Bootup.pack`
        3: The system cannot find the path specified. (os error 3)

Mod I'm trying to use: https://gamebanana.com/mods/327683

Happening on latest commit at time of writing ([daef849](https://github.com/NiceneNerd/ukmm/commit/daef8490e0661434b4f327dd3b834fdada58ea57))

Also, as a side note, the error has a typo (_to **UKKM** mod_ instead of _to **UKMM** mod_)

**Comment by HGStone** [comment]
you dumped your game wrong, the title ID I see is the base game without the
update..  you need to dump the base game with update, then your dump will
match the title ID the ukmm is looking for (and the one listed in the help
and tool tip popups)

**Comment by NiceneNerd** [comment]
It's not dump-related at all, it's just another case where I need to make a parent folder before writing a file. Will be an easy fix this afternoon.
