### ISSUE TITLE
BNP parser expects string for required field

### ISSUE THREAD

**Issue by Benna96** [NiceneNerd/ukmm#35]
Attempting to convert a BNP with a single option results in the following error:  
> Failed to convert BNP to UKKM mod
> 
>     Caused by:
>         0: Failed to parse BNP metadata
>         1: invalid type: boolean `false`, expected a string at line 50 column 25

Changing all instances of `"required": false` to `"required": "false"` in the bnp's info.json "fixes" the issue.  
[Here's one BNP](https://gamebanana.com/dl/895307) with the issue, but I imagine it affects all BNPs with single options.

**Comment by NiceneNerd** [comment]
I ran into an issue trying to set this up where apparently some had empty strings and some had actual booleans. I'll need to rethink how I handle the field to work right for either.
