### ISSUE TITLE
Failed to convert BNP to UKKM mod

### ISSUE THREAD

**Issue by Houyami** [NiceneNerd/ukmm#36]
Failed to convert BNP to UKKM mod

Caused by:
    0: Failed to unpack BNP
    1: Failed to process deepmerge log
    2: File not found in game dump: content/Actor/Pack/Armor_077_Upper.sbactorpack
       (Using source at C:\Users\hyari\AppData\Roaming\yuzu\dump)

Mod being attempted to install: https://gamebanana.com/mods/417544

I redumped, verified the file in question existed but it seems to not want to follow through.

**Comment by NiceneNerd** [comment]
It's a problem with the mod itself. From [the UKMM GB page](https://gamebanana.com/posts/10573521):
> So I've looked into it, and it seems the Linkle BNP actually has a broken `deepmerge log`. Specifically, it seems it contains the Wii U version of the deepmerge log and not a Switch version. In BCML, though, instead throwing an error, the changes made to almost 200 files were simply skipped entirely.
>
> This means the mod really ought to be fixed itself, but if it was working fine despite all those edits not being processed, then you can workaround it by deleting `logs/deepmerge.aamp` from the BNP before putting into UKMM.

**Comment by Cod3xDev** [comment]
I will fix this asap
