### ISSUE TITLE
Various BNP install issues

### ISSUE THREAD

**Issue by Thrumptus** [NiceneNerd/ukmm#38]
I tried upgrading a few BCML 2 BNPs to BCML 3 (see below image) but when installing them in UKMM it immediately crashes, the only one that seemed to work was "Linkle Mod - Dialogue Fix" although it does seem to be behaving slightly strangely in general as when i tried to install it as a BCML 2 BNP it appeared in the mod list, despite throwing an error  

![image](https://user-images.githubusercontent.com/93964920/219521318-9fdd4e03-1ab2-4055-b65c-e2aa8659e819.png)

I've also been having a few issues with other mods as well, not sure if Bootup_USen.pack is necessary but my game is EU so i don't really have a way of getting hold of it, the mods worked fine with BCML though so hoping it's just a bug  

[2023-02-16 20:56:51] INFO Opening mod at C:\Users\Desktop\wildlife__pikachu-npc-cosplay.bnp
[2023-02-16 20:56:51] INFO Extracting BNP…
[2023-02-16 20:56:52] INFO Processing BNP logs…
[2023-02-16 20:56:52] ERROR Failed to convert BNP to UKMM mod

Caused by:
    0: Failed to unpack BNP
    1: File not found in game dump: Pack/Bootup_USen.pack
       (Using source at C:\Users\Documents\Emulation\cemu_1.26.2\mlc01\usr\title)
[2023-02-16 20:57:13] INFO Opening mod at C:\Users\Desktop\hd_map_and_icons_0dc21.bnp
[2023-02-16 20:57:13] INFO Extracting BNP…
[2023-02-16 20:57:24] ERROR Failed to convert BNP to UKMM mod

Caused by:
    0: Failed to unpack BNP
    1: Failed to extract BNP
    2: Io(Custom { kind: InvalidInput, error: "dist overflow" })
[2023-02-16 20:57:33] INFO Opening mod at C:\Users\Desktop\lurelindresslinkle.bnp
[2023-02-16 20:57:33] INFO Extracting BNP…
[2023-02-16 20:57:33] INFO Processing BNP logs…
[2023-02-16 20:57:40] ERROR Failed to convert BNP to UKMM mod

Caused by:
    0: Failed to unpack BNP
    1: File not found in game dump: Pack/Bootup_USen.pack
       (Using source at C:\Users\Documents\Emulation\cemu_1.26.2\mlc01\usr\title)

**Comment by NiceneNerd** [comment]
The Bootup pack stuff is temporary until I decide how I want to manage cross-language stuff. As for the instant crashes, try running from the Command Prompt and seeing what, if any, output there is when it happens.

**Comment by Thrumptus** [comment]
Ah ok, fair enough, apologies if this is a stupid question but by command prompt do you mean a seperate command prompt instance or the one that opens with UKMM?
If you mean UKMMs one then it also crashes
If you mean a sepearate instance how would one go about attempting to install a mod via it

**Comment by NiceneNerd** [comment]
Open the Windows Command Prompt or Powershell to the folder with the UKMM executable (fastest way if you're unfamiliar with be `Shift+Right Click` and then Open Command Window/Open Powershell here), then run `ukmm.exe` and check the output when it crashes.

**Comment by Thrumptus** [comment]
Ah ok cool, will do, ty

**Comment by Thrumptus** [comment]
Sorry for the late response, was away from my pc for a few days
No output in the command prompt

**Comment by NiceneNerd** [comment]
That seems odd. To be clear, you're doing the running UKMM part by typing `ukmm.exe` into the Command Prompt/Powershell, right, not by double-clicking it?

**Comment by Thrumptus** [comment]
Ah, yep, sorry, tired brain lol, i was double clicking, for some reason i interpreted run as install a mod 
I did just try running it from the command prompt as you mentioned but still no dice, it does mention font this time though

**Comment by NiceneNerd** [comment]
Hmm, if nothing else appears when it crashes it makes it very hard to guess what's up. I would try starting by simply deleting the profile folder, then see if it ends up happening again.

**Comment by NiceneNerd** [comment]
Does it happen with mods that aren't BNPs?

**Comment by Thrumptus** [comment]
Tried installing the .7z file from the Darker Nights and Brighter Lights Gamebanana page and that seems to work normally, also tried converting the BCML 2 BNP from the same page to standalone which also works fine, upgrading the same BNP to BCML 3 crashes as normal and turning the upgraded BNP into a standalone works fine

**Comment by NiceneNerd** [comment]
So it happens only with BNPs, it seems?

**Comment by Thrumptus** [comment]
Only with upgraded BCML 2 BNP's it seems

**Comment by Thrumptus** [comment]
Are there any benefits to installing a mod as a BNP instead of another file format?

**Comment by NiceneNerd** [comment]
No

**Comment by Thrumptus** [comment]
Tried with the latest version and everything seemed to install fine although some mods do still throw an error after they're enabled and changes are saved 

Failed to apply pending mod changes

Caused by:
    File not found in game dump: Message/Msg_EUen.product.ssarc
    (Using source at C:\Users\Documents\Emulation\cemu_1.26.2\mlc01\usr\title)

And then again after disabling them and saving

Failed to deploy update to merged mod(s)

Caused by:
    0: Failed to deploy Actor/ActorInfo.product.sbyml to C:\Users\Documents\Emulation\cemu_1.26.2\graphicPacks\BreathOfTheWild_UKMM\content\Actor/ActorInfo.product.sbyml
    1: failed to hardlink file from C:\Users\AppData\Local\ukmm\wiiu\profiles\Old BCML Modset\merged\content\Actor/ActorInfo.product.sbyml to C:\Users\Documents\Emulation\cemu_1.26.2\graphicPacks\BreathOfTheWild_UKMM\content\Actor/ActorInfo.product.sbyml
    2: The system cannot find the file specified. (os error 2)

When the mod errors out, manual deployment is prompted, which also throws an error and the only way i've been able to get rid of the prompt is to reset pending.yml

Failed to deploy Actor/ActorInfo.product.sbyml to C:\Users\Documents\Emulation\cemu_1.26.2\graphicPacks\BreathOfTheWild_UKMM\content\Actor/ActorInfo.product.sbyml

Caused by:
    0: failed to hardlink file from C:\Users\AppData\Local\ukmm\wiiu\profiles\Old BCML Modset\merged\content\Actor/ActorInfo.product.sbyml to C:\Users\Documents\Emulation\cemu_1.26.2\graphicPacks\BreathOfTheWild_UKMM\content\Actor/ActorInfo.product.sbyml
    1: The system cannot find the file specified. (os error 2)

**Comment by CutieCoding** [comment]
> Tried with the latest version and everything seemed to install fine although some mods do still throw an error after they're enabled and changes are saved
> 
> Failed to apply pending mod changes
> 
> Caused by: File not found in game dump: Message/Msg_EUen.product.ssarc (Using source at C:\Users\Documents\Emulation\cemu_1.26.2\mlc01\usr\title)

i get this, using switch mode with a switch dump, 1.6.0 and all DLCs. my dump doesnt have a message folder (atleast in the romfs folder)

**Comment by NiceneNerd** [comment]
Do you use EU or US?

**Comment by Thrumptus** [comment]
All seems to work ok now, still get this error when installing some BNP's, however converting to standalone seems to resolve the issue

Failed to convert BNP to UKMM mod

Caused by:
    0: Failed to unpack BNP
    1: File not found in game dump: Pack/Bootup_USen.pack
       (Using source at C:\Users\Documents\Emulation\cemu_1.26.2\mlc01\usr\title)

**Comment by NiceneNerd** [comment]
Some BNPs include bootup language packs in their pack log, even though they are otherwise handled entirely by the text merger. There is logic for cross-region stuff in the text log handling but not for pack logs. I'll probably just have it filter them entirely.

**Comment by OsoaGH** [comment]
> The Bootup pack stuff is temporary until I decide how I want to manage cross-language stuff.

Is there an ETA for this @NiceneNerd ? I want to know whether it's worth installing BCML or waiting for this to be done.

**Comment by NiceneNerd** [comment]
I believe that is done.
