### ISSUE TITLE
"Help" button leads to wrong page

### ISSUE THREAD

**Issue by AsteroidPizza39** [NiceneNerd/ukmm#4]
The link to "Help" goes https://nicenenerd.github.io/ukmm/packaging.html instead of https://nicenenerd.github.io/ukmm/, results in the picture below instead of the version with actual text at https://nicenenerd.github.io/ukmm/
![image](https://user-images.githubusercontent.com/45804670/209579486-d56f4621-e96d-43cd-9d6d-918067242e89.png)

**Comment by NiceneNerd** [comment]
Fixed in 5d1045c23d219af207e73bab4f3b683cb2dd38f4
