### ISSUE TITLE
Problems with MC_Combos and Farore's Wind

### ISSUE THREAD

**Issue by S22e14** [NiceneNerd/ukmm#46]
When I try to install MC_Combos I get this Error Message:
```
Failed to convert BNP to UKMM mod
Caused by:
    0: Failed to process SARC file Pack/TitleBG.pack
    1: Failed to process Actor/Pack/GameROMPlayer.bactorpack in SARC content/Pack/TitleBG.pack
    2: Failed to parse resource Actor/AS/Player_CutS3.bas in SARC Actor/Pack/GameROMPlayer.sbactorpack
    3: Invalid parameter data for field JudgeOnce: StringRef(
           "True",
```
With this Data Context:

```
Parameter(
  StringRef(
      "True",
  ),
)
```
I have not that much experience in BotW Modding, so my first thought was to change all "True" to "true" in the mentioned File, but after I did this, the Error went on to "Player_CutSF.bas" instead of "Player_CutS3.bas". After changeing this file too, UKMM crashed entirely.

And for Farore's Wind I get this Error Message:
```
Failed to convert BNP to UKMM mod
Caused by:
    0: Failed to unpack BNP
    1: Failed to process gamedata log
    2: BYML file missing key: FlagData missing DataName
```
So now I'm not quite sure wheter it's a problem with both mods themselves or if it's something different.

**Comment by NiceneNerd** [comment]
As best as I can see both of those are indeed problems with the mods in question, just cases where BCML ignored it but UKMM does not. In some such cases the game can still use it (e.g. for all I know it might automatically interpret a non-empty string like "True" as a `true` boolean value), but they're still formally incorrect.
