### ISSUE TITLE
Assorted Suggestions 

### ISSUE THREAD

**Issue by Thrumptus** [NiceneNerd/ukmm#49]
- [ ] When using the "Import from BCML" button, could give users the option to specify their BCML directory and which profile they want to import to (currently just installs to default even if it doesn't exist), also maybe an option to choose what to import, e.g. just mods or just config, or both, migration could have its own page or a drop down in settings
- [x] (Implemented) Could potentially add the ability to select multiple mods for bulk actions such as enabling, disabling and uninstalling etc
- [x] (Implemented) Being able to move mods between profiles or duplicate them into another profile, would be irrelevant if 9 is implemented however 
- [x] Support for BNPs in the install tab
- [ ] The ability to uninstall (or remove in the case of 9 being implemented) a mod from the current profile, a selection of profiles or from all profiles 
- [x] When a mod is uninstalled, if it was also installed under a different profile it will continue to be listed in that profile which sends UKMM into a spiral of errors when selecting it until the profile.yml is reset 
- [ ] If a mod is enabled in a profile but a different profile is selected, stop that mod from loading 
- [ ] ~~Maybe the ability to create multiple different versions of the settings for different profiles, e.g. having a settings profile for Wii U mode linked to one mod profile and a settings profile for Switch mode linked to a different mod profile (has just occurred to me that this mostly already exists, albeit in a slightly different form, so unless there are any general settings which could be useful in this context that I've forgotten, this can be mostly ignored)~~
- [ ] Could have a master mod directory linked to an installed mods page, then from there allow users to install to different profiles or uninstall completely
- [ ] Having the ability to assign categories to mods that have already been installed, i have also noticed mods that require categories when being installed to UKMM don't require them when importing from BCML (not really an issue but just some strange behaviour i thought i should mention) 
- [ ] A button to enable/disable all mods in a profile
- [ ] ~~A toggle for mod reordering, enabled by default~~
- [ ] ~~Very minor nitpick but the letters in the word yes in the deploy tab when auto deploy is on appear to be incorrectly spaced, might be intentional or a limitation in which case i apologise~~
- [ ]  The small scroll bar to the right of the mod list appears to be inverted when clicking and dragging

**Comment by NiceneNerd** [comment]
I should note that (2) is already implemented with Ctrl-Click. (12) shouldn't be necessary like it is in BCML since you can drag and drop at any time. Many of the rest of these do make sense, though.

**Comment by Thrumptus** [comment]
Ah I didn't realise that, awesome, I wrote 12 as I was imagining a windows style system of clicking and dragging a box over files to select them, which would be inconvenient as people could accidentally reorder mods whilst trying to select them, but you've definitely got a better solution

**Comment by Thrumptus** [comment]
Also found that toggling a mod off and on, and then saving and deploying errors out, not sure how much can be done about this but unlikely to normally be an issue, I usually just do it trigger a redeploy so maybe an additional permanent deploy button could be useful instead of just one that pops up when a change is made in UKMM

**Comment by OsoaGH** [comment]
Looks like 3 is done, might be worth ticking these off as they're added

**Comment by Thrumptus** [comment]
Good idea, haven't been keeping track of development as of late so didn't realise new features were added, i've updated the original comment to reflect the changes

**Comment by NiceneNerd** [comment]
I changed it to a checklist so it's easier to keep track

**Comment by OsoaGH** [comment]
I'm personally most interested in 9 being added, that's something I really wished was in BCML and seems like a really useful feature.

**Comment by OsoaGH** [comment]
> I don't think I understand what 9 means, come to think of it.

I'm pretty sure they're saying that they want a profile (or something similar to it), where everything in that profile is shared to all other profiles (or ones that have been selected), including all changes. Kind of like a base for the selected profiles to build off of, so if you edit one thing in a profile you don't need to edit the same thing in multiple profiles if they have the same mod.

**Comment by Thrumptus** [comment]
> > I don't think I understand what 9 means, come to think of it.
> 
> I'm pretty sure they're saying that they want a profile (or something similar to it), where everything in that profile is shared to all other profiles (or ones that have been selected), including all changes. Kind of like a base for the selected profiles to build off of, so if you edit one thing in a profile you don't need to edit the same thing in multiple profiles if they have the same mod.

That's an interesting idea actually, tbh what i was originally envisioning was something like a list of installed mods, and then from there you can manage them, deleting them or adding them to a profile etc (although when adding to a profile the mod would remain in the main list as well), and then actual mod loading is done based off of the selected profile rather than the main mod list, currently iirc installing a mod to another profile requires installing the mod again like normal despite it already being installed, although i may be completely off here as i haven't had a chance to do any tinkering recently to refresh my memory

**Comment by Thrumptus** [comment]
I don't think i'm explaining myself very well so might try and create a general mockup of what i mean
