### ISSUE TITLE
Add support for "updating" mods

### ISSUE THREAD

**Issue by AsteroidPizza39** [NiceneNerd/ukmm#5]
This feature would increase QoL for mod developers. My idea is that you would right click the mod in your `Mods` section, and one of the options would be `Create Update`. This would open the mod in the `Package` window, auto-filling all the information from the mod you selected except for the `Source`. This way, mod creators wouldn't have to switch tabs to manually copy the information. The current system of showing the selected mod on the right side of the screen is a workaround for this, but a dedicated feature would make it much simpler.

**Comment by NiceneNerd** [comment]
I have a couple ideas along these lines in planning, so keep an eye out in the next build (or next, or maybe next...).

**Comment by AsteroidPizza39** [comment]
There should be a Platform option when creating a mod. Because 0.2.6 doesn't consider Switch a valid version in Settings (despite it being selectable), all mods I've packaged on this version are considered Wii U mods. This resulted in needing to manually edit the meta.yml. being able to package a mod for a version that isn't selected also makes it easier to play on one platform and create mods for another without needing to switch back and forth.

Another suggestion is an (open ended) "Other" option for the mod category, alongside the addition of "Compatibility Patch" as a default category.

**Comment by NiceneNerd** [comment]
Packaging is only possible for the mode that's currently active. You can make mods for the other platform by switching to that mode while you do it.
