### ISSUE TITLE
Updater can't update because exe in use

### ISSUE THREAD

**Issue by Benna96** [NiceneNerd/ukmm#51]
Launched UKMM, and it was offering to update, so gave that a try.

It can't copy in the new exe because the exe is in use... which is no wonder, seeing as how UKMM is open while it's trying to do this... It should probably close UKMM before trying to copy the exe?
![image](https://user-images.githubusercontent.com/23498000/224462319-68453ed7-5637-4c3b-8f9a-d2a3c504ce05.png)

**Comment by NiceneNerd** [comment]
Yes, this needs to be fixed and never actually worked while testing, just never finished with the platform-specific scripts it would need. Coming soon
