### ISSUE TITLE
Error when trying to install Island Expansion mod

### ISSUE THREAD

**Issue by Meepster-836** [NiceneNerd/ukmm#54]
This might be an issue with the mod itself, but I figured I'd post it here just in case (this is also my first post on github):

---------------------------------------------------------------------------------------------------------------------------------------------------
Failed to convert BNP to UKMM mod

Caused by:

    0: Failed to unpack BNP at `crates\uk-manager\src\bnp.rs@390:42`

    1: Failed to process gamedata log at `crates\uk-manager\src\bnp.rs@290:14`

    2: Parsing YAML failed: check failed: m_state->flags & SSCL
           at D:\a\ukmm\ukmm\target\release\build\ryml-fc6e07615cab6ef2\out\cxxbridge\crate\ryml/include/ryml.h:28361

    3: check failed: m_state->flags & SSCL
           at D:\a\ukmm\ukmm\target\release\build\ryml-fc6e07615cab6ef2\out\cxxbridge\crate\ryml/include/ryml.h:28361

---------------------------------------------------------------------------------------------------------------------------------------------------

**Comment by Meepster-836** [comment]
I am running on version 0.6.0 of UKMM.

**Comment by NiceneNerd** [comment]
Looks like this one is indeed the mod, for some strange reason there's a gamedata flag with an empty name, and it doesn't like that. Try removing that entry from the `logs/gamedata.yml` file inside the BNP, or else give it a shot with the graphic pack version (indeed, in general prefer graphic pack versions to BNPs for mods that don't already use UKMM's format).
