### ISSUE TITLE
Issue when downloading mod [MAC"

### ISSUE THREAD

**Issue by ImUltik** [NiceneNerd/ukmm#57]
Basically any mod i download i get an issue, or i am doing something wrong.

<img width="1312" alt="Screenshot 2023-03-12 at 12 26 09" src="https://user-images.githubusercontent.com/104308255/224541482-1b85e4ea-c9ac-4b93-a668-69be914f2c65.png">

**Comment by NiceneNerd** [comment]
Looks like you didn't set your game dump settings yet.
