### ISSUE TITLE
Zelda's Ballad Incompatability

### ISSUE THREAD

**Issue by voodoochiledev** [NiceneNerd/ukmm#60]
Attempting to add Zelda's Ballad and encountering the following error when enabling.

```
Failed to apply pending mod changes

Caused by:
    0: Failed to build SARC file Actor/Pack/Armor_005_Head.sbactorpack at `crates\uk-mod\src\unpack.rs@659:22`
    1: Failed to build file Actor/Physics/Npc_Zelda_Miko.bphysics for SARC at `crates\uk-mod\src\unpack.rs@681:18`
    2: No base version for file Actor/Physics/Npc_Zelda_Miko.bphysics at `crates\uk-mod\src\unpack.rs@612:14
```

No other mods are enabled. Occurs for both the "Replacement Animations" and "Link's Animations" version from https://gamebanana.com/mods/168244. Results in the mod mostly loading, but without face textures for player.
I see in the changelogs there were recent issues with this mod, potentially related? . Both had to be unpacked and repacked from .rar into .zip / .7z to install, but I doubt that'd be the cause.

Environment: Windows 10
CEMU Version 1.26.2f
UKMM Version 0.6.0

**Comment by NiceneNerd** [comment]
I've seen this reported once or twice but have never been able to reproduce the error. I do get the black faces, but no error in UKMM. 

What are your dump settings?

**Comment by voodoochiledev** [comment]
The error message I kept getting seems to have gone away after I reboot. Must have been a red herring. Still getting the no-texture issue but sounds like you know about that one.

Dump settings anyways:
Unpacked.
Base: `E:\<name>\WiiU_UH_Games\DATA\EMULATORS\Cemu\GAMES\The Legend of Zelda Breath of the Wild [ALZE01]\content\`
Update: `E:\<name>\WiiU_UH_Games\DATA\EMULATORS\Cemu\BIN\mlc01\usr/title\0005000E/101C9400/content\`
DLC: `E:\<name>\WiiU_UH_Games\DATA\EMULATORS\Cemu\BIN\mlc01\usr/title\0005000C/101C9400/content/0010`

**Comment by Drakonas** [comment]
I get this with just Hyrule Rebalance v7.11 enabled. I migrated from BCML using the button, prior to setting up any settings with UKMM. Not sure if I was supposed to set up settings first.

**Comment by NiceneNerd** [comment]
Can anyone confirm if this persists on v0.8.2?

**Comment by hazelnot** [comment]
Assuming you mean the black textures issue, yes, I'm having this issue on 0.9.0 on Steam Deck. Zelda's face appears completely black, and her body textures are pixelated and garbled.

**Comment by AnityEx** [comment]
tried today, zelda's ballad still not working completely on ukmm, its so weird only her skin is the one with problems and all the outfits seem fine unless it changes her hair

**Comment by CoherentThought** [comment]
Zelda's Ballad still has texture issues.
