### ISSUE TITLE
Command line arguments not outputting to console

### ISSUE THREAD

**Issue by Benna96** [NiceneNerd/ukmm#62]
Using command line arguments used to output something to the console. Now there's no output at all, not even for `--help`, whose entire purpose is to print helpful things to the console.
![image](https://user-images.githubusercontent.com/23498000/226101736-1ba8c1b3-53d0-4bef-bcea-cb1ae395b9eb.png)

Seems to have been broken in 0.3.1.
![image](https://user-images.githubusercontent.com/23498000/226102050-7a746121-39f2-4eac-8ff6-ccb4d852e965.png)

**Comment by NiceneNerd** [comment]
Hmm, seems when I got rid of the superfluous console window on Windows it also suppressed all console output. Apparently it's very hard to make the same binary on Windows run either exclusively as a console app or exclusively a GUI with no console. This needs further investigation.

**Comment by ArchLeaders** [comment]
This still isn't working for me (0.7.1), it just opens the GUI

**Comment by ArchLeaders** [comment]
**Update:** The CLI commands work, but things like `--help` don't (they just run the application)
