### ISSUE TITLE
index out of bounds: the len is 598 but the index is 598

### ISSUE THREAD

**Issue by jeremysolo** [NiceneNerd/ukmm#68]
When attempting to migrate from BCML I get  the following error

index out of bounds: the len is 598 but the index is 598

**Comment by NiceneNerd** [comment]
I'd need the complete error message to figure anything out, though chances are high it's a mod-specific problem

**Comment by jeremysolo** [comment]
That is the complete message actually. When I click details it just says the same thing again

**Comment by NiceneNerd** [comment]
Run with verbose logging enabled, and post the full log output

**Comment by Luminarus25** [comment]
Having this issue too, turned on Verbose logging and this is what it said.

index out of bounds: the len is 960 but the index is 1030

**Comment by NiceneNerd** [comment]
Is that the entire log from the beginning? I won't be able to find anything unless I know basically what activity it was in the middle of when this happened

**Comment by NiceneNerd** [comment]
Fixed with 3f445ea3a5a7369489ce7680127d93d9b6fc53d3
