### ISSUE TITLE
UKMM won't create/read settings files

### ISSUE THREAD

**Issue by Foxlass** [NiceneNerd/ukmm#69]
Every time I open UKMM I get the following error:

> [2023-03-30 4:19:09] INFO Started ukmm
> [2023-03-30 4:19:10] ERROR Failed to read settings file:
> failed to open file `C:\Users\minec\AppData\Roaming\ukmm\settings.yml`
> [2023-03-30 4:19:10] INFO Loading default settings instead
> [2023-03-30 4:19:10] INFO Initializing mod manager
> [2023-03-30 4:19:10] INFO Current profile: Default
> [2023-03-30 4:19:10] INFO Initializing deployment manager
> [2023-03-30 4:19:10] WARN Could not load pending deployment data:
> failed to open file `C:\Users\minec\AppData\Local\ukmm\wiiu\pending.yml`
> [2023-03-30 4:19:10] INFO No files pending deployment
> [2023-03-30 4:19:10] INFO Logger initialized
> [2023-03-30 4:19:16] DEBUG Verbose logging enabled
> 

I have tried running the program as administrator but had no sucess.

**Comment by NiceneNerd** [comment]
Did you at any point configure and save your settings?

**Comment by Foxlass** [comment]
> Did you at any point configure and save your settings?

Yes, and when I try to, it crashes to desktop.

**Comment by NiceneNerd** [comment]
Is there any output at all leftover if you run it from a console and have verbose logging on when it crashes?
