### ISSUE TITLE
Mac Support

### ISSUE THREAD

**Issue by SecondBeta** [NiceneNerd/ukmm#7]
Are there any plans to support Mac systems? Considering BCML does not do this either.

**Comment by ArchLeaders** [comment]
I don't think the developer owns a mac, so full support is unlikely. But unlike BCML, everything is assembly compiled, so you could probably build from source on a mac and use it.

**Comment by NiceneNerd** [comment]
I don't have any way to develop for Mac, but TBH *most* of the codebase would probably work on it as-is. I don't know if [roead](https://github.com/NiceneNerd/roead), [zarchive-rs](https://github.com/NiceneNerd/zarchive-rs), or [ryml](https://github.com/NiceneNerd/ryml) will compile on Mac without modification, though.

If anyone with the skills wants to investigate this, I would be interested to see it come to pass, but unless I'm unexpectedly donated a Mac there's little I can do myself.

I will leave this issue open precisely for the possibility of other contributors, though.

**Comment by aem111607** [comment]
The build fails on roxmltree for me

**Comment by aem111607** [comment]
> I don't have any way to develop for Mac, but TBH _most_ of the codebase would probably work on it as-is. I don't know if [roead](https://github.com/NiceneNerd/roead), [zarchive-rs](https://github.com/NiceneNerd/zarchive-rs), or [ryml](https://github.com/NiceneNerd/ryml) will compile on Mac without modification, though.
> 
> If anyone with the skills wants to investigate this, I would be interested to see it come to pass, but unless I'm unexpectedly donated a Mac there's little I can do myself.
> 
> I will leave this issue open precisely for the possibility of other contributors, though.

Roead zarchive-rs and ryml all compiled fine for me.

**Comment by NiceneNerd** [comment]
What's the exact error for ryml?

**Comment by aem111607** [comment]
> What's the exact error for ryml?

[log.txt](https://github.com/NiceneNerd/ukmm/files/10787059/log.txt)

**Comment by NiceneNerd** [comment]
What's your GCC version?

**Comment by aem111607** [comment]
> What's your GCC version?

I'm using clang 14

**Comment by NiceneNerd** [comment]
You may have Clang, but ryml seems to be compiling with GCC, which I believe is the normal `cxx_build` behavior. So what's your GCC version?

**Comment by aem111607** [comment]
> You may have Clang, but ryml seems to be compiling with GCC, which I believe is the normal `cxx_build` behavior. So what's your GCC version?

Oh, 12.2.0

**Comment by NiceneNerd** [comment]
See what happens if you run it with this environment variable set: `CXXFLAGS=-std=c++11`

**Comment by aem111607** [comment]
> See what happens if you run it with this environment variable set: `CXXFLAGS=-std=c++11`

No change

**Comment by neebyA** [comment]
@aem111607 I think https://github.com/NiceneNerd/ryml/pull/1 should solve that issue, for ryml at least. That should leave only zarchive-rs with macOS problems. I'm able to fix zarchive-rs' compiler errors and compile it, but I think it's still having trouble during linking. I'll try to work on it some more if I have time, but any help is appreciated.

@NiceneNerd can you take a look at the PR? Thanks

**Comment by aem111607** [comment]
> @aem111607 I think [NiceneNerd/ryml#1](https://github.com/NiceneNerd/ryml/pull/1) should solve that issue, for ryml at least. That should leave only zarchive-rs with macOS problems. I also fixed zarchive-rs' compiler errors and can compile it ([NiceneNerd/zarchive-rs#1](https://github.com/NiceneNerd/zarchive-rs/pull/1)), but it's having trouble during linking if I use GNU gcc.
> 
> With the above changes, I was able to compile ukmm using clang, but it panics at runtime. I'll work on it some more if I have time; any help is appreciated.
> 
> @NiceneNerd can you take a look at the PRs? Thanks
> 
> Edit: https://github.com/NiceneNerd/ukmm/tree/3d03d55495c239500178e07a6f2a8a5391bd5dd1 is the last commit that gets me to the GUI. I haven't tried loading any mods or anything though so I'm not entirely sure if it even works. Later commits get me this:
> 
> ```
> thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', crates/uk-ui/src/lib.rs:25:55
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> An unrecoverable error occured. Error details: called `Option::unwrap()` on a `None` value
> ```
> 
> This makes sense to me as the [next commit](https://github.com/NiceneNerd/ukmm/commit/31e71cf23b4b0df1059f47fa35d6760e80d8897b) seems to do some processing on the output of `gsettings get org.gnome.desktop.interface font-name`, and macOS doesn't use GNOME. I think this would need some additional code to deal with macOS

I tested it with the linkle mod and it _appears_ to be working flawlessly

**Comment by Lukas1h** [comment]
Hey, @aem111607, is there any way you could share your build for macOS?

**Comment by NiceneNerd** [comment]
As of 0.7.0, macOS builds are provided. Yay, time to close this.
