### ISSUE TITLE
crash: Illegal instruction

### ISSUE THREAD

**Issue by foresto** [NiceneNerd/ukmm#70]
When I open a .bnp file, after a few seconds of the "Processing... Extracting BNP..." screen, it crashes without writing anything to the log file. The terminal shows the following output:

    Illegal instruction

v0.7.1 on Linux

Is it possible that the Linux build is using AVX2 CPU instructions, or some other instructions that aren't universal?

**Comment by NiceneNerd** [comment]
Turn on trace-level debugging with the `RUST_LOG=trace` environmental variable and verbose logging enabled, then see what the last log item is

**Comment by NiceneNerd** [comment]
One more thing: what's your CPU?

**Comment by imsl0wer** [comment]
Having the exact same Problem on latest Arch Linux.
