### ISSUE TITLE
Wont run on windows 10

### ISSUE THREAD

**Issue by MrKittenK** [NiceneNerd/ukmm#71]
Anytime I try to run the application i get this error

C:\Users\Test\Desktop\bnp files>thread 'main' panicked at 'failed to create opengl context: Error { raw_code: Some(-1073274731), raw_os_message: Some("OS Error -1073274731 (FormatMessageW() returned error 317) (os error -1073274731)"), kind: Misc }', C:\Users\runneradmin\.cargo\git\checkouts\egui-e93c8b2747e99fbf\3803a32\crates\eframe\src\native\run.rs:405:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
An unrecoverable error occured. Error details: failed to create opengl context: Error { raw_code: Some(-1073274731), raw_os_message: Some("OS Error -1073274731 (FormatMessageW() returned error 317) (os error -1073274731)"), kind: Misc }

any ideas?

Thank you

**Comment by NiceneNerd** [comment]
Do you get exactly the same error every time, or does it vary?

**Comment by MrKittenK** [comment]
Everytime. 
If I run from a windows CMD window. 
If I just launch the exe I get nothing. 
Doesn't even show up for a brief moment in task manager. 

I have checked my visual studio install etc
All up to date, added in any extra installs as noted etc.

**Comment by NiceneNerd** [comment]
But is even the OS error being exactly `-1073274731` the same every time?

**Comment by NiceneNerd** [comment]
From as much information as I can determine, this may be an issue related to a graphics driver or thereabouts.

**Comment by MrKittenK** [comment]
-1073274731 

yes every time, i will update all drivers and report back, thank you for your time and help
