### ISSUE TITLE
Failed to parse BNP metadata: invalid type: integer

### ISSUE THREAD

**Issue by foresto** [NiceneNerd/ukmm#80]
When trying to open [noyigaspawns.bnp](https://gamebanana.com/mods/49845), ukmm v0.7.1 fails with this message:

    Failed to convert BNP to UKMM mod

    Caused by:
        0: Failed to parse BNP metadata at `crates/uk-manager/src/bnp.rs@396:58`
        1: invalid type: integer `1`, expected a string at line 6 column 15

**Comment by NiceneNerd** [comment]
For now, change the version in the `info.json` to a string, e.g. `"1"`. I'll make it take either.

**Comment by NiceneNerd** [comment]
Fixed with b1d2c899c670230e0d996dcefc3904d29de8e7aa
