### ISSUE TITLE
Addition Mods & Multiplayer [READ ISSUE]

### ISSUE THREAD

**Issue by GamingInfinite** [NiceneNerd/ukmm#82]
Bear in mind I'm writing this at like 2AM and need sleep.  Not very well documented or tested.

UKMM seems to not like mods that add things, like at all (eg. Outfit additions like the Magical Girl Linkle Skin).  On a related note the Multiplayer mod that just recently released UKMM also really doesn't like, trying to refresh merge really ****s with it

**Comment by NiceneNerd** [comment]
Details plz?

**Comment by HGStone** [comment]
The multiplayer instructions explicitly say to use bcml, and from what the
devs say when I asked them about it is that ukmm is currently not supported

**Comment by GamingInfinite** [comment]
Sorry like I said was really tired and it was like 2am.
When hitting refresh merge with just the 2 bnps for multiplayer it says this

> Failed to apply pending mod changes
> 
> Caused by:
>     0: Failed to clear merged folder at `crates\uk-manager\src\deploy.rs@486:44`
>     1: C:\Users\Zachariah Collins\AppData\Local\ukmm\wiiu\profiles\Multiplayer\merged at `crates\uk-manager\src\util.rs@14:45`
>     2: The system cannot find the file specified. (os error 2)

(I installed the mods to ukmm by importing from BCML)

Trying to boot the game obviously fails because it's not actually a functional merge.  I then tried to install them separately directly into UKMM which actually does function, but what doesn't happen is when installed via BCML it adds a Multiplayer Utilities Graphics Pack to Cemu as well, which I don't see present after deleting it and installing via UKMM.  It readded itself upon reinstalling to BCML.  I then tried to boot (with the utilities present) into Multiplayer, but no dice, the game just crashes after a couple of seconds instead of just not starting at all.
[ukmm multi crash log.txt](https://github.com/NiceneNerd/ukmm/files/11163226/ukmm.multi.crash.log.txt) [pastebin](https://pastebin.com/xT81jUMD)
The log itself doesn't show any weird signs that I could see, even comparing BCML loaded and UKMM loaded individually, the only difference being different lettering.  I tried looking at the verbose log of UKMM but scrolling through that just made my head hurt, and is a SUPER long text file, so just install both Multiplayer BNPs yourself.  What was weirder still to me is that UKMM is supposed to support BCML 3 bnps right? But when importing from BCML, linkle mods wouldn't merge either, but trying a manual install soon to see if it works properly that way.

**Comment by NiceneNerd** [comment]
Does `C:\Users\Zachariah Collins\AppData\Local\ukmm\wiiu\profiles\Multiplayer\merged` exist?

**Comment by GamingInfinite** [comment]
yeah it does.

**Comment by NiceneNerd** [comment]
Is it always that same error when merging? If the path exists but Windows is claiming it doesn't, something truly fishy is going on

**Comment by GamingInfinite** [comment]
Not home right now but you might just try installing it yourself and seeing if it breaks in a similar way
