### ISSUE TITLE
UKMM doesn't add a new font

### ISSUE THREAD

**Issue by Proofeek** [NiceneNerd/ukmm#85]
I have a mod that adds a new font to Font_US.bfarc, there are also modified original fonts, after packaging a graphicpack and activating the mod, in the game modified fonts works fine, but there is no new font. 

It should look like this:
![image](https://user-images.githubusercontent.com/78957574/230628470-8514664d-72f0-4b54-bf11-a6fdd947bc29.png)

But it looks like this:
![image](https://user-images.githubusercontent.com/78957574/230628835-bfcabe11-7258-4bca-8426-103c6e958e69.png)

The zip archive has this font (Special_01.bffnt):
![image](https://user-images.githubusercontent.com/78957574/230629249-dbbaf763-6f6d-438a-9ee8-f52fac6af2b6.png)

![230628470-8514664d-72f0-4b54-bf11-a6fdd947bc29](https://user-images.githubusercontent.com/78957574/230630148-595308e6-0380-44d8-9207-a2c666a03f3a.png)

**Comment by Proofeek** [comment]
I found another example. A mod adds a new file _"name"_.bflim to Bootup.pack\Layout\Common.sblarc\timg\ (there is no file with that name in the original \timg\ folder) and it is also not displayed in the game: 

Graphic Pack (_"name"_.bflim is this blue circle):
![image](https://user-images.githubusercontent.com/78957574/230943869-116bf5eb-5b63-4a3d-8248-d80c79f870ea.png)
UKMM:
![image](https://user-images.githubusercontent.com/78957574/230943524-5880c444-a648-4f47-80c7-79c96d6b7a8d.png)

**Comment by NiceneNerd** [comment]
Does this persist on the latest build (0.8.2)?

**Comment by Proofeek** [comment]
Yes
