### ISSUE TITLE
Importing from BCML allows for duplicate mods

### ISSUE THREAD

**Issue by Thrumptus** [NiceneNerd/ukmm#86]
When importing from BCML, UKMM doesn't appear to check other currently installed mods, allowing multiple different versions of a mod to be listed under different profiles, in my case the mod i had before the import threw an error every time i tried to interact with it, complaining about a lack of manifest iirc, it's been a while since this happened though so my memory is a little patchy

**Comment by Thrumptus** [comment]
My current theory is that the pre-import mod was overwritten but i don't remember well enough to confirm this was the case

**Comment by NiceneNerd** [comment]
So far it does check for duplicate names. I'm a little confused

**Comment by Thrumptus** [comment]
I'm not entirely sure how i managed it either, might try and do a bit more research, definitely did have two different versions of the same mod installed though
