### ISSUE TITLE
Packaging improvements

### ISSUE THREAD

**Issue by Proofeek** [NiceneNerd/ukmm#87]
**(1)** It would be great to have a choice of files that should be included in the package so that the mod author knows exactly what will be included in the mod. When selecting the source, a window would appear with checkboxes. By default, the files identified by UKMM as modified will be checked. However, the mod author will also have the ability to check or uncheck files.

For example, if the source is a graphic pack with Font_EU.sbfarc, Font_US.sbfarc, and Bootup.pack, then such a window will appear:
<img src="https://user-images.githubusercontent.com/78957574/230765958-f97ed3b1-9418-4808-ab49-90c462b2976e.png" width="284" height="520">

**(2)** Why are there so many files in the zip archive after packing? As far as I understand, most of them are not used anyway. If this is really the case, it would be nice for the zip archive to contain only the necessary files.
![image](https://user-images.githubusercontent.com/78957574/230766982-3941245f-e9b8-4b6f-9b1b-97eb9467293e.png)

**Comment by NiceneNerd** [comment]
1. Is there a reason there would be files that should not be included?
2. Only files which are actually used are included. Looks like font files might be packaged awkwardly, though.
