### ISSUE TITLE
Automatically fix the scaling issue for steam deck

### ISSUE THREAD

**Issue by anka-213** [NiceneNerd/ukmm#88]
Many people have reported the same issue with the window scaling to an unusable level on steam deck. It's good that there's a workaround: running with

```
env WINIT_X11_SCALE_FACTOR=1.0 ./ukmm
```

but in order to find that workaround you first need to ~find the issue here on github and find the workaround in the thread.~

----

**Edit:** or look in the troubleshooting section in the documentation. Sorry for not looking carefully first!

----

Would it be possible to permanently fix the issue from your side, e.g. by including a launcher script in the bundle, like this comment suggested:

> Huh. Thanks for the solution and sorry for the duplicate issue. Seeing as the fix is somewhat non-obvious, might it be worth packing the steam-deck release with a start.sh that applies the environment variable? Or adding a line in the documentation, maybe.

_Originally posted by @Saevarion in https://github.com/NiceneNerd/ukmm/issues/59#issuecomment-1470158935_
            
or fixing it through some other changes in the code? ~If not, could it be documented somewhere?~

Thank you for your great work!

**Comment by HGStone** [comment]
That workaround is already in the documentation.
https://nicenenerd.github.io/ukmm/troubleshooting.html

**Comment by anka-213** [comment]
@HGStone Oh, whoops, sorry about that! Thanks for pointing it out!

**Comment by NiceneNerd** [comment]
Done at 8273935dd6cb8fa7fa555e1ceda76d3ad967e70d.
