### ISSUE TITLE
Hyrule Rebalance v7.11 fails to apply.

### ISSUE THREAD

**Issue by Drakonas** [NiceneNerd/ukmm#89]
Apologies. Accidentally pushed the issue without adding more. Curse you Return key.

Tried deleting profile and all mods, then installing fresh.

If I install the Hyrule Rebalance (I disable the Stamina and Flurry Rush optional addons) it just simply fails to apply with the below error:

````
Failed to apply pending mod changes

Caused by:
    0: Failed to build SARC file Actor/Pack/Armor_269_Upper.sbactorpack at `crates\uk-mod\src\unpack.rs@679:22`
    1: Failed to build file Actor/ModelList/Armor_160_Upper.bmodellist for SARC at `crates\uk-mod\src\unpack.rs@701:18`
    2: No base version for file Actor/ModelList/Armor_160_Upper.bmodellist at `crates\uk-mod\src\unpack.rs@632:14`
````

I should note. If I disable all mods, then refresh merge, I get this:

````
Failed to apply pending mod changes

Caused by:
    0: Failed to build SARC file Actor/Pack/Armor_269_Upper.sbactorpack at `crates\uk-mod\src\unpack.rs@679:22`
    1: Failed to build file Actor/AIProgram/Armor.baiprog for SARC at `crates\uk-mod\src\unpack.rs@701:18`
    2: No base version for file Actor/AIProgram/Armor.baiprog at `crates\uk-mod\src\unpack.rs@632:14`
````

I have verified all my files in Cemu using online verifier again for posterity. All came up clean.

Base: `D:\Games\WiiU\Games\The Legend of Zelda Breath of the Wild [ALZE0101]\content`
Update: `D:/Games/WiiU/MLC/usr/title/0005000e/101c9400/content`
DLC: `D:/Games/WiiU/MLC/usr/title/0005000c/101c9400/content/0010`

Wait, why is the Update and DLC using forward slashes after importing Cemu settings?

**Comment by Drakonas** [comment]
Must've been a Windows 10/11 NTFS file lock issue. A restart fixed this. Curse you NTFS.... Ugh.

**Comment by EncampedMars801** [comment]
I'm having this exact issue, except on Linux with an Ext4 filesystem, not NTFS... I assume you haven't had this happen to you again?

**Comment by NiceneNerd** [comment]
Does restarting UKMM and/or your PC make any difference?

**Comment by EncampedMars801** [comment]
Doesn't seem to

**Comment by NiceneNerd** [comment]
And other mods work fine?

**Comment by EncampedMars801** [comment]
I mean I remember a mod here or there not working, but that was a couple months ago so A those were probably fixed and B I don't even remember what they were at this point. But yeah in general all other mods install and work fine.

**Comment by EncampedMars801** [comment]
Ok so uh, git-pulled and compiled the latest changes, and it now works? tbh im not sure if it was something there that fixed it or some other random aspect of my computer fixing it, but hey, it works now soo
