### ISSUE TITLE
Girly Animations corrupts titleBG.pack when enabled

### ISSUE THREAD

**Issue by Gear4luffy1** [NiceneNerd/ukmm#92]
When i enable Girly Animations on UKMM i get no errors but on botw startup (atmosphere cfw) it crashes immediately.

This also happened with linkle 3 but i just decided to use linkle 2 instead because that one worked.

I have no idea why this is happing other then that when i delete titlebg.pack it works but obviously doesnt load any mods.

has this has happened to anyone else? and if so how did you solve it?

**Comment by avsdfag** [comment]
This also happened to me. I tried to uninstall then reinstall linkle 3, now I'm getting the following error:
```
Failed to apply pending mod changes

Caused by:
    0: Failed to build SARC file Actor/Pack/Armor_171_Upper.sbactorpack at `crates/uk-mod/src/unpack.rs@679:22`
    1: Failed to build file Actor/Physics/Armor_005_Upper.bphysics for SARC at `crates/uk-mod/src/unpack.rs@701:18`
    2: No base version for file Actor/Physics/Armor_005_Upper.bphysics at `crates/uk-mod/src/unpack.rs@632:14`
```

**Comment by Gear4luffy1** [comment]
I've gotten that error before and what usually works for me is unchecking every mod and then refresh merge and after that enable your mods and apply them one by one

**Comment by avsdfag** [comment]
So it looks like both linkle 3 and girly animations crash the game on startup. Have you tried merging these mods with BCML?

**Comment by Gear4luffy1** [comment]
I can't use bcml cuz I can't install python over 3.5 cuz I don't have admin on the computer in using

**Comment by NiceneNerd** [comment]
Does this continue in v0.8.1 if the mods are reinstalled?

**Comment by Gear4luffy1** [comment]
I'll have to reinstall the game to check
