### ISSUE TITLE
Error Code (Mac)

### ISSUE THREAD

**Issue by SpaghettiSMM2** [NiceneNerd/ukmm#93]
Sorry For Bugging Everybody Bout My Problems.. Anyway I Think I Found Out Why This Wont Work..

Last login: Thu Apr 13 07:10:22 on ttys004
/Volumes/OS_DEV/ukmm/ukmm ; exit;                                               
(base) K——T——r@K- -iMac ~ % /Volumes/OS_DEV/ukmm/ukmm ; exit;
dyld: Symbol not found: __ZTTNSt3__114basic_ifstreamIcNS_11char_traitsIcEEEE
  Referenced from: /Volumes/OS_DEV/ukmm/ukmm (**which was built for Mac OS X 12.0**)
  Expected in: /usr/lib/libc++.1.dylib
 in /Volumes/OS_DEV/ukmm/ukmm
zsh: abort      /Volumes/OS_DEV/ukmm/ukmm
Saving session...
...copying shared history...cp: /Users/k——t——-/.zsh_history: Permission denied

...saving history...shell_session_save_history:14: permission denied: /Users/k——t——-/.zsh_history
truncating history files...shell_session_save_history:21: can't read history file /Users/k——t——-/.zsh_history

[Process completed]

And Then It Just Stops There.. So Is That Saying I Need **Mac OS X 12.0??!**

**(Mine Is Big Sur 11.7)** 

What Should I Do??

**Comment by NiceneNerd** [comment]
The automated builds use macOS 12, so if it won't run on 11, you can try building from source.

**Comment by SpaghettiSMM2** [comment]
@NiceneNerd What Does This Mean? 

Nothing else special is required. Generate a release build by running `cargo build --release` in the root repo folder. It may take a while.

**Comment by neebyA** [comment]
Try using the release on my fork here: https://github.com/neebyA/ukmm/releases/tag/v0.7.1

I lowered the minimum deployment target in the GitHub Action to macOS 11, then created that release.

Remember that on macOS you will need to clear the quarantine attribute to run the executable:
```bash
cd ~/Downloads/
unzip ukmm-v0.7.1-macos.zip
xattr -d com.apple.quarantine ukmm
./ukmm
```

**Comment by SpaghettiSMM2** [comment]
@NiceneNerd I'll Try It. Thanks!

**Comment by SpaghettiSMM2** [comment]
OH MY GOD I GOT IT!!!!! Thanks So Much Man!!!!!

**Comment by SpaghettiSMM2** [comment]
You Are A Life Saver!!

**Comment by SpaghettiSMM2** [comment]
But Can I Just Edit The Game Folders Through The SD Card? Does It Have To Be DIRECTLY On The Computer? So If I Have The Game On An SD Card, Connect It To Computer, Will It Work??
