### ISSUE TITLE
Failing to apply pending mod changes

### ISSUE THREAD

**Issue by RetroGamerAndre** [NiceneNerd/ukmm#95]
Hello, whenever I try to apply mod changes an error occurs and says the following:
Failed to apply pending mod changes

Caused by:
    called `Result::unwrap()` on an `Err` value: TypeError("U32", "Int")
    
unsure of what is going wrong, but if something can be done that would be most appreciated.

**Comment by NiceneNerd** [comment]
Paste the full log
